<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Изучение-и-подготовка-данных" data-toc-modified-id="Изучение-и-подготовка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Изучение и подготовка данных</a></span></li><li><span><a href="#Анализ-различных-моделей-для-определения-стоимости-автомобиля" data-toc-modified-id="Анализ-различных-моделей-для-определения-стоимости-автомобиля-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Анализ различных моделей для определения стоимости автомобиля</a></span><ul class="toc-item"><li><span><a href="#Линейная-регрессия" data-toc-modified-id="Линейная-регрессия-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Линейная регрессия</a></span></li><li><span><a href="#LightGBM" data-toc-modified-id="LightGBM-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>LightGBM</a></span></li><li><span><a href="#XGBoost" data-toc-modified-id="XGBoost-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>XGBoost</a></span></li><li><span><a href="#CatBoost" data-toc-modified-id="CatBoost-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>CatBoost</a></span></li></ul></li><li><span><a href="#Выводы" data-toc-modified-id="Выводы-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Выводы</a></span></li></ul></div>

# Описание проекта
Сервис по продаже автомобилей с пробегом разрабатывает приложение для привлечения новых клиентов. В нём можно быстро узнать рыночную стоимость своего автомобиля. В вашем распоряжении исторические данные: технические характеристики, комплектации и цены автомобилей. Вам нужно построить модель для определения стоимости.

Заказчику важны:
- качество предсказания;
- скорость предсказания;
- время обучения.

# Инструкция по выполнению проекта:
Чтобы усилить исследование, не ограничивайтесь градиентным бустингом. Попробуйте более простые модели — иногда они работают лучше. Это редкие случаи, которые легко пропустить, если всегда применять только бустинг. Поэкспериментируйте и сравните характеристики моделей: скорость работы, точность результата.
- Загрузите и подготовьте данные.
- Обучите разные модели. Для каждой попробуйте различные гиперпараметры.
- Проанализируйте скорость работы и качество моделей.

Примечания:
- Для оценки качества моделей применяйте метрику RMSE.
- Самостоятельно освойте библиотеку LightGBM и её средствами постройте модели градиентного бустинга.
- Время выполнения ячейки кода Jupyter Notebook можно получить специальной командой. Найдите её.
- Поскольку модель градиентного бустинга может обучаться долго, измените у неё только два-три параметра.
- Если перестанет работать Jupyter Notebook, удалите лишние переменные оператором del.

# Описание данных
- Признаки
    - DateCrawled — дата скачивания анкеты из базы
    - VehicleType — тип автомобильного кузова
    - RegistrationYear — год регистрации автомобиля
    - Gearbox — тип коробки передач
    - Power — мощность (л. с.)
    - Model — модель автомобиля
    - Kilometer — пробег (км)
    - RegistrationMonth — месяц регистрации автомобиля
    - FuelType — тип топлива
    - Brand — марка автомобиля
    - NotRepaired — была машина в ремонте или нет
    - DateCreated — дата создания анкеты
    - NumberOfPictures — количество фотографий автомобиля
    - PostalCode — почтовый индекс владельца анкеты (пользователя)
    - LastSeen — дата последней активности пользователя
- Целевой признак
    - Price — цена (евро)

## Изучение и подготовка данных

In [1]:
import pandas as pd
import numpy as np

from tqdm.auto import tqdm
tqdm.pandas()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from datetime import datetime
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [3]:
# Код для чтения данных
df_autos = pd.read_csv('df_autos.csv')  # Локальный путь

In [4]:
df_autos.head()

DateCrawled  Price VehicleType  RegistrationYear Gearbox  Power  \
0  2016-03-24 11:52:17    480         NaN              1993  manual      0   
1  2016-03-24 10:58:45  18300       coupe              2011  manual    190   
2  2016-03-14 12:52:21   9800         suv              2004    auto    163   
3  2016-03-17 16:54:04   1500       small              2001  manual     75   
4  2016-03-31 17:25:20   3600       small              2008  manual     69   

   Model  Kilometer  RegistrationMonth  FuelType       Brand NotRepaired  \
0   golf     150000                  0    petrol  volkswagen         NaN   
1    NaN     125000                  5  gasoline        audi         yes   
2  grand     125000                  8  gasoline        jeep         NaN   
3   golf     150000                  6    petrol  volkswagen          no   
4  fabia      90000                  7  gasoline       skoda          no   

           DateCreated  NumberOfPictures  PostalCode             LastSeen  
0  2016-03-24 00:00:00                 0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00                 0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00                 0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00                 0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00                 0       60437  2016-04-06 10:17:21

In [5]:
df_autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354369 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        354369 non-null  object
 1   Price              354369 non-null  int64 
 2   VehicleType        316879 non-null  object
 3   RegistrationYear   354369 non-null  int64 
 4   Gearbox            334536 non-null  object
 5   Power              354369 non-null  int64 
 6   Model              334664 non-null  object
 7   Kilometer          354369 non-null  int64 
 8   RegistrationMonth  354369 non-null  int64 
 9   FuelType           321474 non-null  object
 10  Brand              354369 non-null  object
 11  NotRepaired        283215 non-null  object
 12  DateCreated        354369 non-null  object
 13  NumberOfPictures   354369 non-null  int64 
 14  PostalCode         354369 non-null  int64 
 15  LastSeen           354369 non-null  object
dtypes: int64(7), object(

В данных много пропусков, причем разное количество. Следовательно пропуски не в одних и тех же строках, поэтому рассмотрим каждый столбец с пропусками!

In [6]:
# Найдем дубликаты
df_autos[df_autos.duplicated() == True]

DateCrawled  Price VehicleType  RegistrationYear Gearbox  \
171088  2016-03-08 18:42:48   1799       coupe              1999    auto   
231258  2016-03-28 00:56:10   1000       small              2002  manual   
258109  2016-04-03 09:01:15   4699       coupe              2003    auto   
325651  2016-03-18 18:46:15   1999       wagon              2001  manual   

        Power   Model  Kilometer  RegistrationMonth  FuelType          Brand  \
171088    193     clk      20000                  7    petrol  mercedes_benz   
231258     83   other     150000                  1    petrol         suzuki   
258109    218     clk     125000                  6    petrol  mercedes_benz   
325651    131  passat     150000                  7  gasoline     volkswagen   

       NotRepaired          DateCreated  NumberOfPictures  PostalCode  \
171088          no  2016-03-08 00:00:00                 0       89518   
231258          no  2016-03-28 00:00:00                 0       66589   
258109         yes  2016-04-03 00:00:00                 0       75196   
325651          no  2016-03-18 00:00:00                 0       36391   

                   LastSeen  
171088  2016-03-09 09:46:57  
231258  2016-03-28 08:46:21  
258109  2016-04-07 09:44:54  
325651  2016-03-18 18:46:15

In [7]:
# Удалим дубликаты
df_autos = df_autos[df_autos.duplicated() != True]
df_autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354365 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        354365 non-null  object
 1   Price              354365 non-null  int64 
 2   VehicleType        316875 non-null  object
 3   RegistrationYear   354365 non-null  int64 
 4   Gearbox            334532 non-null  object
 5   Power              354365 non-null  int64 
 6   Model              334660 non-null  object
 7   Kilometer          354365 non-null  int64 
 8   RegistrationMonth  354365 non-null  int64 
 9   FuelType           321470 non-null  object
 10  Brand              354365 non-null  object
 11  NotRepaired        283211 non-null  object
 12  DateCreated        354365 non-null  object
 13  NumberOfPictures   354365 non-null  int64 
 14  PostalCode         354365 non-null  int64 
 15  LastSeen           354365 non-null  object
dtypes: int64(7), object(

Заполним пропуски в колонке с моделью автомобиля, для этого изучим уникальные значения моделей.

In [8]:
df_autos['Model'].unique()

array(['golf', nan, 'grand', 'fabia', '3er', '2_reihe', 'other', 'c_max',
       '3_reihe', 'passat', 'navara', 'ka', 'polo', 'twingo', 'a_klasse',
       'scirocco', '5er', 'meriva', 'arosa', 'c4', 'civic', 'transporter',
       'punto', 'e_klasse', 'clio', 'kadett', 'kangoo', 'corsa', 'one',
       'fortwo', '1er', 'b_klasse', 'signum', 'astra', 'a8', 'jetta',
       'fiesta', 'c_klasse', 'micra', 'vito', 'sprinter', '156', 'escort',
       'forester', 'xc_reihe', 'scenic', 'a4', 'a1', 'insignia', 'combo',
       'focus', 'tt', 'a6', 'jazz', 'omega', 'slk', '7er', '80', '147',
       '100', 'z_reihe', 'sportage', 'sorento', 'v40', 'ibiza', 'mustang',
       'eos', 'touran', 'getz', 'a3', 'almera', 'megane', 'lupo', 'r19',
       'zafira', 'caddy', 'mondeo', 'cordoba', 'colt', 'impreza',
       'vectra', 'berlingo', 'tiguan', 'i_reihe', 'espace', 'sharan',
       '6_reihe', 'panda', 'up', 'seicento', 'ceed', '5_reihe', 'yeti',
       'octavia', 'mii', 'rx_reihe', '6er', 'modus', 'fox'

In [9]:
# Вывод строк с моделью 'other'
df_autos.query('Model == "other"')

DateCrawled  Price  VehicleType  RegistrationYear Gearbox  \
7       2016-03-21 18:54:38      0        sedan              1980  manual   
24      2016-03-13 20:40:49    500        sedan              1990  manual   
38      2016-04-01 17:45:07  11900        other              2002  manual   
39      2016-03-25 15:50:30   1500          bus              1984  manual   
52      2016-04-04 10:57:36   1400          NaN              2016  manual   
...                     ...    ...          ...               ...     ...   
354290  2016-03-11 14:45:44   2500        small              2007  manual   
354302  2016-03-12 08:37:15   5990          bus              1984    auto   
354316  2016-03-07 19:58:44   3300        coupe              1957  manual   
354325  2016-03-12 16:48:14  12800  convertible              1991  manual   
354331  2016-03-15 01:51:20   2999        coupe              2003  manual   

        Power  Model  Kilometer  RegistrationMonth  FuelType          Brand  \
7          50  other      40000                  7    petrol     volkswagen   
24        118  other     150000                 10    petrol  mercedes_benz   
38        129  other     150000                 11  gasoline     volkswagen   
39         70  other     150000                  8  gasoline  mercedes_benz   
52         55  other       5000                  1       NaN        hyundai   
...       ...    ...        ...                ...       ...            ...   
354290     60  other     125000                  3    petrol        hyundai   
354302      0  other      70000                  4    petrol      chevrolet   
354316     40  other     100000                 11    petrol        trabant   
354325    211  other     150000                  7    petrol        porsche   
354331    143  other     150000                  3    petrol  mercedes_benz   

       NotRepaired          DateCreated  NumberOfPictures  PostalCode  \
7               no  2016-03-21 00:00:00                 0       19348   
24             yes  2016-03-13 00:00:00                 0       35390   
38              no  2016-04-01 00:00:00                 0       10551   
39              no  2016-03-25 00:00:00                 0       22767   
52             NaN  2016-04-04 00:00:00                 0       34454   
...            ...                  ...               ...         ...   
354290         NaN  2016-03-11 00:00:00                 0       18107   
354302         NaN  2016-03-12 00:00:00                 0       87600   
354316          no  2016-03-07 00:00:00                 0       10317   
354325          no  2016-03-12 00:00:00                 0       21147   
354331         yes  2016-03-14 00:00:00                 0       72766   

                   LastSeen  
7       2016-03-25 16:47:58  
24      2016-03-13 20:40:49  
38      2016-04-05 12:47:30  
39      2016-03-27 03:17:02  
52      2016-04-06 12:45:43  
...                     ...  
354290  2016-03-17 21:46:52  
354302  2016-03-24 23:47:48  
354316  2016-03-08 06:45:48  
354325  2016-04-07 06:46:00  
354331  2016-04-05 13:17:05  

[24420 rows x 16 columns]

Среди всех моделей есть значение 'other' и оно у разных марок автомобилей, значит все пропуски можно заменить на это значение!

In [10]:
df_autos['Model'] = df_autos['Model'].fillna(value='other')
df_autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354365 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        354365 non-null  object
 1   Price              354365 non-null  int64 
 2   VehicleType        316875 non-null  object
 3   RegistrationYear   354365 non-null  int64 
 4   Gearbox            334532 non-null  object
 5   Power              354365 non-null  int64 
 6   Model              354365 non-null  object
 7   Kilometer          354365 non-null  int64 
 8   RegistrationMonth  354365 non-null  int64 
 9   FuelType           321470 non-null  object
 10  Brand              354365 non-null  object
 11  NotRepaired        283211 non-null  object
 12  DateCreated        354365 non-null  object
 13  NumberOfPictures   354365 non-null  int64 
 14  PostalCode         354365 non-null  int64 
 15  LastSeen           354365 non-null  object
dtypes: int64(7), object(

Заполним пропуски в колонке с коробкой передач автомобиля, для этого изучим уникальные значения.

In [11]:
df_autos['Gearbox'].unique()

array(['manual', 'auto', nan], dtype=object)

Все пропуски заменим на значение 'indefinite' (неопределенный)

In [12]:
df_autos['Gearbox'] = df_autos['Gearbox'].fillna(value='indefinite')

Заполним пропуски в колонке с типом топлива автомобиля, для этого изучим уникальные значения.

In [13]:
df_autos['FuelType'].unique()

array(['petrol', 'gasoline', nan, 'lpg', 'other', 'hybrid', 'cng',
       'electric'], dtype=object)

Среди значений так же есть 'other', пропуски заменим на это значение.

In [14]:
df_autos['FuelType'] = df_autos['FuelType'].fillna(value='other')

Заполним пропуски в колонке с информацией о ремонте автомобиля, для этого изучим уникальные значения.

In [15]:
df_autos['NotRepaired'].unique()

array([nan, 'yes', 'no'], dtype=object)

In [16]:
df_autos['NotRepaired'].value_counts()

no     247158
yes     36053
Name: NotRepaired, dtype: int64

Будем считать пропуск отсутствием ремонта, поэтому заменим 'nan' на 'no'

In [17]:
df_autos['NotRepaired'] = df_autos['NotRepaired'].fillna(value='no')

Заполним пропуски в колонке с кузовом автомобиля, для этого изучим уникальные значения.

In [18]:
df_autos['VehicleType'].unique()

array([nan, 'coupe', 'suv', 'small', 'sedan', 'convertible', 'bus',
       'wagon', 'other'], dtype=object)

In [19]:
len(df_autos['Model'].unique())

250

In [20]:
len(df_autos['Brand'].unique())

40

Напишем функцию, которая:
- находит все строки с требуемыми маркой и моделью авто
- возвращает самый встречаемый тип кузова среди этих строк

In [21]:
def model_brands_pairs(df_autos=df_autos):
    # Создадим новую таблицу, куда будет записываться модели, марки и наиболее часто встречаемый тип кузова
    df_test = pd.DataFrame(columns=['model', 'brand', 'vehicle_type'])
    
    min_index = 0

    for model in tqdm(df_autos['Model'].unique()):
        for brand in df_autos['Brand'].unique():
            # Найдем все строки с требуемыми маркой и моделью авто
            df_temp = df_autos[(df_autos['Brand'] == brand) & (df_autos['Model'] == model)]
            # Выберем ненулевой длины срезы
            if len(df_temp) == 0:
                continue
            # найдем наиболее часто встречаемый тип кузова при таком сочетании марки и модели
            vehicle_type = df_temp['VehicleType'].value_counts().index[0]
            # в минимальный индекс записываем модель, бренд, тип кузова
            df_test.loc[min_index, 'model'] = model
            df_test.loc[min_index, 'brand'] = brand
            df_test.loc[min_index, 'vehicle_type'] = vehicle_type
            # обновляем индекс
            min_index += 1
    return df_test

In [22]:
try:
    # Откроем таблицу сочетаний модели, марки и  типа кузова
    df_test = pd.read_csv('pair_model_brand.csv')
except FileNotFoundError:
    # если таблицы нет, сгенерируем ее и сохраним
    df_test = model_brands_pairs()
    df_test.to_csv('pair_model_brand.csv', index=False)

In [23]:
df_test.head()

model       brand vehicle_type
0   golf  volkswagen        sedan
1  other  volkswagen        small
2  other        audi        wagon
3  other        jeep          suv
4  other       skoda        small

In [24]:
# Заменим пропуски в типе кузова в исходной таблице на наиболее встречаемый при
# определенном сочетании марки и модели
def replace_vehicle_nan(df_autos=df_autos):
    for index in tqdm(df_autos[df_autos['VehicleType'].isna()].index):
        model = df_autos.loc[index, 'Model']
        brand = df_autos.loc[index, 'Brand']
        vehicle_type = df_test[(df_test['brand'] == brand)
                               &(df_test['model'] == model)]['vehicle_type'].values[0]
        df_autos.loc[index, 'VehicleType'] = vehicle_type
    return df_autos

In [25]:
try:
    # Откроем таблицу сочетаний модели, марки и  типа кузова
    df_autos_new = pd.read_csv('df_autos_new.csv')
except FileNotFoundError:
    # если таблицы нет, сгенерируем ее и сохраним
    df_autos_new = replace_vehicle_nan()
    df_autos_new.to_csv('df_autos_new.csv', index=False)

In [26]:
# Найдем минимальную стоимость
df_autos_new['Price'].min()

0

Минимальная стоимость равна нулю, это ошибка, которая внесет в обучение модели неточности, посмотрим какое количество объявлений с нулевой стоимостью

In [27]:
len(df_autos_new.query('Price == 0'))

10772

In [28]:
df_autos_new = df_autos_new.query('Price != 0')

In [29]:
# Найдем количесвто объявлений с единичной стоимостью!
len(df_autos_new.query('Price == 1'))

1189

In [30]:
# Таких объявлений мало? поэтому удалим их
df_autos_new = df_autos_new.query('Price != 1')

In [31]:
df_autos_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 342404 entries, 0 to 354364
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        342404 non-null  object
 1   Price              342404 non-null  int64 
 2   VehicleType        342404 non-null  object
 3   RegistrationYear   342404 non-null  int64 
 4   Gearbox            342404 non-null  object
 5   Power              342404 non-null  int64 
 6   Model              342404 non-null  object
 7   Kilometer          342404 non-null  int64 
 8   RegistrationMonth  342404 non-null  int64 
 9   FuelType           342404 non-null  object
 10  Brand              342404 non-null  object
 11  NotRepaired        342404 non-null  object
 12  DateCreated        342404 non-null  object
 13  NumberOfPictures   342404 non-null  int64 
 14  PostalCode         342404 non-null  int64 
 15  LastSeen           342404 non-null  object
dtypes: int64(7), object(

In [32]:
# Удалим колонки с датой скачивания анкеты, датой создания анкеты и датой последней сессии
df_autos_new = df_autos_new.drop(['DateCrawled', 'DateCreated', 'LastSeen'], axis=1)
df_autos_new.head()

Price VehicleType  RegistrationYear Gearbox  Power  Model  Kilometer  \
0    480       sedan              1993  manual      0   golf     150000   
1  18300       coupe              2011  manual    190  other     125000   
2   9800         suv              2004    auto    163  grand     125000   
3   1500       small              2001  manual     75   golf     150000   
4   3600       small              2008  manual     69  fabia      90000   

   RegistrationMonth  FuelType       Brand NotRepaired  NumberOfPictures  \
0                  0    petrol  volkswagen          no                 0   
1                  5  gasoline        audi         yes                 0   
2                  8  gasoline        jeep          no                 0   
3                  6    petrol  volkswagen          no                 0   
4                  7  gasoline       skoda          no                 0   

   PostalCode  
0       70435  
1       66954  
2       90480  
3       91074  
4       60437

In [33]:
df_autos_new = df_autos_new.drop(['RegistrationMonth'], axis=1)
df_autos_new.head()

Price VehicleType  RegistrationYear Gearbox  Power  Model  Kilometer  \
0    480       sedan              1993  manual      0   golf     150000   
1  18300       coupe              2011  manual    190  other     125000   
2   9800         suv              2004    auto    163  grand     125000   
3   1500       small              2001  manual     75   golf     150000   
4   3600       small              2008  manual     69  fabia      90000   

   FuelType       Brand NotRepaired  NumberOfPictures  PostalCode  
0    petrol  volkswagen          no                 0       70435  
1  gasoline        audi         yes                 0       66954  
2  gasoline        jeep          no                 0       90480  
3    petrol  volkswagen          no                 0       91074  
4  gasoline       skoda          no                 0       60437

Ошибки обработаны, пропуски заполнены, можно переходить к обучению моделей!

In [34]:
# Найдем машины старше 1900 и старше 2021, очевидно, что это ошибки
df_autos_new.query('RegistrationYear < 1900 or RegistrationYear > 2021')

Price VehicleType  RegistrationYear     Gearbox  Power   Model  \
12946      49       sedan              5000  indefinite      0    golf   
15870    1700       sedan              3200  indefinite      0   other   
16062     190       wagon              1000  indefinite      0  mondeo   
17271     700       small              9999  indefinite      0   other   
17346    6500       sedan              8888  indefinite      0   other   
...       ...         ...               ...         ...    ...     ...   
331749     99       sedan              9999  indefinite      0     1er   
334963  12000       sedan              4000  indefinite    500    golf   
338825     50       sedan              3000  indefinite   3000    golf   
340755    700       sedan              1600      manual   1600      a3   
351678  11500       small              1800  indefinite     16   other   

        Kilometer FuelType           Brand NotRepaired  NumberOfPictures  \
12946        5000    other      volkswagen          no                 0   
15870        5000    other  sonstige_autos          no                 0   
16062        5000    other            ford          no                 0   
17271       10000    other            opel          no                 0   
17346       10000    other  sonstige_autos          no                 0   
...           ...      ...             ...         ...               ...   
331749      10000    other             bmw          no                 0   
334963       5000    other      volkswagen          no                 0   
338825     100000    other      volkswagen         yes                 0   
340755     150000   petrol            audi          no                 0   
351678       5000   petrol            fiat          no                 0   

        PostalCode  
12946        74523  
15870        33649  
16062        47166  
17271        21769  
17346        55262  
...            ...  
331749        1239  
334963       57392  
338825       23992  
340755       86343  
351678       16515  

[131 rows x 12 columns]

In [35]:
# Удалим эти значения
df_autos_new = df_autos_new.query('1900 <= RegistrationYear <= 2021')

In [36]:
# Найдем все авто, у которых мощность больше 500
df_autos_new.query('Power > 500')

Price VehicleType  RegistrationYear     Gearbox  Power    Model  \
1816     3200       small              2004      manual   1398  corolla   
4060     3100       sedan              2005      manual    953     colt   
5328      500       wagon              1999      manual   1001    astra   
6296      599       small              2002      manual    603    matiz   
6504     3000       small              2009      manual    771    punto   
...       ...         ...               ...         ...    ...      ...   
348964    250       small              1999      manual   1241  ypsilon   
351943   1500         bus              2001      manual   1001   zafira   
353489  12500       sedan              2017      manual   2000    other   
353629   2400       sedan              2007      manual    650       c2   
354256    399       other              1994  indefinite   1103      3er   

        Kilometer  FuelType       Brand NotRepaired  NumberOfPictures  \
1816         5000    petrol      toyota          no                 0   
4060       150000  gasoline  mitsubishi          no                 0   
5328       150000    petrol        opel          no                 0   
6296         5000    petrol   chevrolet         yes                 0   
6504       125000    petrol        fiat          no                 0   
...           ...       ...         ...         ...               ...   
348964     150000    petrol      lancia         yes                 0   
351943       5000  gasoline        opel          no                 0   
353489      60000  gasoline    chrysler          no                 0   
353629     150000    petrol     citroen          no                 0   
354256     150000     other         bmw          no                 0   

        PostalCode  
1816         22043  
4060         60326  
5328         33154  
6296         44379  
6504         40721  
...            ...  
348964       28259  
351943       66117  
353489       44145  
353629       45277  
354256       56235  

[417 rows x 12 columns]

In [37]:
# Всего 417 значений, в основном это ошибки, но ничего страшного если удалим несколько машин
# с реальной такой мощностью
df_autos_new = df_autos_new.query('Power <= 500')

In [38]:
# Найдем количество автомобилей с нулевой мощностью
len(df_autos_new.query('Power == 0'))

35778

In [39]:
df_autos_new.head(10)

Price  VehicleType  RegistrationYear Gearbox  Power    Model  Kilometer  \
0     480        sedan              1993  manual      0     golf     150000   
1   18300        coupe              2011  manual    190    other     125000   
2    9800          suv              2004    auto    163    grand     125000   
3    1500        small              2001  manual     75     golf     150000   
4    3600        small              2008  manual     69    fabia      90000   
5     650        sedan              1995  manual    102      3er     150000   
6    2200  convertible              2004  manual    109  2_reihe     150000   
8   14500          bus              2014  manual    125    c_max      30000   
9     999        small              1998  manual    101     golf     150000   
10   2000        sedan              2004  manual    105  3_reihe     150000   

    FuelType       Brand NotRepaired  NumberOfPictures  PostalCode  
0     petrol  volkswagen          no                 0       70435  
1   gasoline        audi         yes                 0       66954  
2   gasoline        jeep          no                 0       90480  
3     petrol  volkswagen          no                 0       91074  
4   gasoline       skoda          no                 0       60437  
5     petrol         bmw         yes                 0       33775  
6     petrol     peugeot          no                 0       67112  
8     petrol        ford          no                 0       94505  
9      other  volkswagen          no                 0       27472  
10    petrol       mazda          no                 0       96224

In [40]:
def replace_power_zero(df_autos_new=df_autos_new):
    for row in tqdm(df_autos_new.index):
        if df_autos_new['Power'][row] == 0:
            df_autos_new['Power'][row] = df_autos_new[(df_autos_new['Model'] == df_autos_new['Model'][row])
                                                      & (df_autos_new['Power'] != 0 )]['Power'].mean()
        else:
            continue
    return df_autos_new

In [41]:
try:
    # Откроем таблицу сочетаний модели, марки и  типа кузова
    df_autos_new_01 = pd.read_csv('df_autos_new_01.csv')
except FileNotFoundError:
    # если таблицы нет, сгенерируем ее и сохраним
    df_autos_new_01 = replace_power_zero()
    df_autos_new_01.to_csv('df_autos_new_01.csv', index=False)

In [42]:
df_autos_new_01.head(10)

Price  VehicleType  RegistrationYear Gearbox  Power    Model  Kilometer  \
0    480        sedan              1993  manual  104.0     golf     150000   
1  18300        coupe              2011  manual  190.0    other     125000   
2   9800          suv              2004    auto  163.0    grand     125000   
3   1500        small              2001  manual   75.0     golf     150000   
4   3600        small              2008  manual   69.0    fabia      90000   
5    650        sedan              1995  manual  102.0      3er     150000   
6   2200  convertible              2004  manual  109.0  2_reihe     150000   
7  14500          bus              2014  manual  125.0    c_max      30000   
8    999        small              1998  manual  101.0     golf     150000   
9   2000        sedan              2004  manual  105.0  3_reihe     150000   

   FuelType       Brand NotRepaired  NumberOfPictures  PostalCode  
0    petrol  volkswagen          no                 0       70435  
1  gasoline        audi         yes                 0       66954  
2  gasoline        jeep          no                 0       90480  
3    petrol  volkswagen          no                 0       91074  
4  gasoline       skoda          no                 0       60437  
5    petrol         bmw         yes                 0       33775  
6    petrol     peugeot          no                 0       67112  
7    petrol        ford          no                 0       94505  
8     other  volkswagen          no                 0       27472  
9    petrol       mazda          no                 0       96224

In [43]:
df_autos_new_01['Power'] = df_autos_new_01['Power'].round()
df_autos_new_01.dropna(subset = ['Power'], inplace = True)
df_autos_new_01.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341855 entries, 0 to 341855
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Price             341855 non-null  int64  
 1   VehicleType       341855 non-null  object 
 2   RegistrationYear  341855 non-null  int64  
 3   Gearbox           341855 non-null  object 
 4   Power             341855 non-null  float64
 5   Model             341855 non-null  object 
 6   Kilometer         341855 non-null  int64  
 7   FuelType          341855 non-null  object 
 8   Brand             341855 non-null  object 
 9   NotRepaired       341855 non-null  object 
 10  NumberOfPictures  341855 non-null  int64  
 11  PostalCode        341855 non-null  int64  
dtypes: float64(1), int64(5), object(6)
memory usage: 33.9+ MB


In [44]:
df_autos_new_01['Power'] = df_autos_new_01['Power'].astype('int')

## Анализ различных моделей для определения стоимости автомобиля

In [45]:
# Выполним прямое кодирование таблицы с обходом дамми-ловушки
df_autos_new_ohe = pd.get_dummies(df_autos_new_01, drop_first=True)
df_autos_new_ohe

Price  RegistrationYear  Power  Kilometer  NumberOfPictures  \
0         480              1993    104     150000                 0   
1       18300              2011    190     125000                 0   
2        9800              2004    163     125000                 0   
3        1500              2001     75     150000                 0   
4        3600              2008     69      90000                 0   
...       ...               ...    ...        ...               ...   
341851   1150              2000    125     150000                 0   
341852   2200              2005    125      20000                 0   
341853   1199              2000    101     125000                 0   
341854   9200              1996    102     150000                 0   
341855   3400              2002    100     150000                 0   

        PostalCode  VehicleType_convertible  VehicleType_coupe  \
0            70435                        0                  0   
1            66954                        0                  1   
2            90480                        0                  0   
3            91074                        0                  0   
4            60437                        0                  0   
...            ...                      ...                ...   
341851       26624                        0                  0   
341852       39576                        0                  0   
341853       26135                        1                  0   
341854       87439                        0                  0   
341855       40764                        0                  0   

        VehicleType_other  VehicleType_sedan  ...  Brand_skoda  Brand_smart  \
0                       0                  1  ...            0            0   
1                       0                  0  ...            0            0   
2                       0                  0  ...            0            0   
3                       0                  0  ...            0            0   
4                       0                  0  ...            1            0   
...                   ...                ...  ...          ...          ...   
341851                  0                  0  ...            0            0   
341852                  0                  1  ...            0            0   
341853                  0                  0  ...            0            1   
341854                  0                  0  ...            0            0   
341855                  0                  0  ...            0            0   

        Brand_sonstige_autos  Brand_subaru  Brand_suzuki  Brand_toyota  \
0                          0             0             0             0   
1                          0             0             0             0   
2                          0             0             0             0   
3                          0             0             0             0   
4                          0             0             0             0   
...                      ...           ...           ...           ...   
341851                     0             0             0             0   
341852                     1             0             0             0   
341853                     0             0             0             0   
341854                     0             0             0             0   
341855                     0             0             0             0   

        Brand_trabant  Brand_volkswagen  Brand_volvo  NotRepaired_yes  
0                   0                 1            0                0  
1                   0                 0            0                1  
2                   0                 0            0                0  
3                   0                 1            0                0  
4                   0                 0            0                0  
...               ...               ...          ...              ...  
341851              

In [46]:
# Выделим переменные признаки и признак, который нужно предсказать для каждой таблицы
features = df_autos_new_ohe.drop('Price', axis=1)
target = df_autos_new_ohe['Price']
# Отделим валидационную выборку (25%) от первоначальных данных
features_train, features_test, target_train, target_test = train_test_split(
    features, target, test_size=0.25, random_state=12345)

### Линейная регрессия

In [47]:
start_time = datetime.now()

model_lin_reg = LinearRegression()
result_lin_reg = cross_val_score(model_lin_reg, features_train, target_train,
                                 scoring='neg_mean_squared_error', cv=5).mean()
end_time = datetime.now()
time_lin_reg = end_time - start_time
print('RMSE модели линейной регрессии:', round(abs(result_lin_reg)**0.5, 2))
print('Время выполнения кода:', time_lin_reg)

RMSE модели линейной регрессии: 2752.61
Время выполнения кода: 0:00:10.579188


In [48]:
# Найдем время обучения и предсказания модели линейной регрессии
start_time = datetime.now()
model_lin_reg.fit(features_train, target_train)
end_time = datetime.now()
time_lr_fit = end_time - start_time

start_time = datetime.now()
predictions=model_lin_reg.predict(features_test)
end_time = datetime.now()
time_lr_predict = end_time - start_time
print('Время обучения модели линейной регрессии:', time_lr_fit)
print('Время предсказания модели линейной регрессии:', time_lr_predict)

Время обучения модели линейной регрессии: 0:00:02.601249
Время предсказания модели линейной регрессии: 0:00:00.145788


### LightGBM

In [49]:
df_autos_new_01.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341855 entries, 0 to 341855
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Price             341855 non-null  int64 
 1   VehicleType       341855 non-null  object
 2   RegistrationYear  341855 non-null  int64 
 3   Gearbox           341855 non-null  object
 4   Power             341855 non-null  int64 
 5   Model             341855 non-null  object
 6   Kilometer         341855 non-null  int64 
 7   FuelType          341855 non-null  object
 8   Brand             341855 non-null  object
 9   NotRepaired       341855 non-null  object
 10  NumberOfPictures  341855 non-null  int64 
 11  PostalCode        341855 non-null  int64 
dtypes: int64(6), object(6)
memory usage: 33.9+ MB


In [50]:
# Поменяем тип данных на категориальный в следующих стобцах
for col in ['VehicleType', 'Gearbox', 'Model', 'FuelType', 'Brand', 'NotRepaired']:
    df_autos_new_01[col] = df_autos_new_01[col].astype('category')

In [51]:
df_autos_new_01.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341855 entries, 0 to 341855
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype   
---  ------            --------------   -----   
 0   Price             341855 non-null  int64   
 1   VehicleType       341855 non-null  category
 2   RegistrationYear  341855 non-null  int64   
 3   Gearbox           341855 non-null  category
 4   Power             341855 non-null  int64   
 5   Model             341855 non-null  category
 6   Kilometer         341855 non-null  int64   
 7   FuelType          341855 non-null  category
 8   Brand             341855 non-null  category
 9   NotRepaired       341855 non-null  category
 10  NumberOfPictures  341855 non-null  int64   
 11  PostalCode        341855 non-null  int64   
dtypes: category(6), int64(6)
memory usage: 20.6 MB


In [54]:
# Выделим переменные признаки и признак, который нужно предсказать для каждой таблицы
features_categorial = df_autos_new_01.drop('Price', axis=1)
target_categorial = df_autos_new_01['Price']
# Отделим валидационную выборку (20%) от первоначальных данных
features_train_categorial, features_test_categorial, target_train_categorial, target_test_categorial = train_test_split(
    features_categorial, target_categorial, test_size=0.20, random_state=12345)

In [55]:
start_time = datetime.now()

model_lgbm = LGBMRegressor(random_state=12345)
params_lgbm = {'n_estimators' : [100, 200, 500],
               'max_depth' : range(2, 7),
               'num_leaves': [20, 30, 40],
               'learning_rate': [0.03, 0.1, 0.5]}

search_lgbm = GridSearchCV(estimator=model_lgbm, param_grid=params_lgbm, scoring='neg_mean_squared_error',
                           verbose=3, cv=3)
result_lgbm = search_lgbm.fit(features_train_categorial , target_train_categorial)

end_time = datetime.now()
time_lgbm = end_time - start_time

Fitting 3 folds for each of 135 candidates, totalling 405 fits
[CV 1/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=20;, score=-6253206.365 total time=   0.3s
[CV 2/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=20;, score=-6181485.762 total time=   0.3s
[CV 3/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=20;, score=-6155917.584 total time=   0.3s
[CV 1/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=30;, score=-6253206.365 total time=   0.3s
[CV 2/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=30;, score=-6181485.762 total time=   0.3s
[CV 3/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=30;, score=-6155917.584 total time=   0.4s
[CV 1/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=40;, score=-6253206.365 total time=   0.3s
[CV 2/3] END learning_rate=0.03, max_depth=2, n_estimators=100, num_leaves=40;, score=-6181485.762 total time= 

[CV 1/3] END learning_rate=0.03, max_depth=4, n_estimators=200, num_leaves=40;, score=-3346585.236 total time=   0.7s
[CV 2/3] END learning_rate=0.03, max_depth=4, n_estimators=200, num_leaves=40;, score=-3366359.168 total time=   0.7s
[CV 3/3] END learning_rate=0.03, max_depth=4, n_estimators=200, num_leaves=40;, score=-3363644.976 total time=   0.7s
[CV 1/3] END learning_rate=0.03, max_depth=4, n_estimators=500, num_leaves=20;, score=-3032008.818 total time=   1.5s
[CV 2/3] END learning_rate=0.03, max_depth=4, n_estimators=500, num_leaves=20;, score=-3050104.711 total time=   1.5s
[CV 3/3] END learning_rate=0.03, max_depth=4, n_estimators=500, num_leaves=20;, score=-3041832.940 total time=   1.5s
[CV 1/3] END learning_rate=0.03, max_depth=4, n_estimators=500, num_leaves=30;, score=-3032008.818 total time=   1.5s
[CV 2/3] END learning_rate=0.03, max_depth=4, n_estimators=500, num_leaves=30;, score=-3050104.711 total time=   1.5s
[CV 3/3] END learning_rate=0.03, max_depth=4, n_estimato

[CV 2/3] END learning_rate=0.1, max_depth=2, n_estimators=100, num_leaves=30;, score=-4087827.147 total time=   0.3s
[CV 3/3] END learning_rate=0.1, max_depth=2, n_estimators=100, num_leaves=30;, score=-4093464.858 total time=   0.3s
[CV 1/3] END learning_rate=0.1, max_depth=2, n_estimators=100, num_leaves=40;, score=-4064992.995 total time=   0.3s
[CV 2/3] END learning_rate=0.1, max_depth=2, n_estimators=100, num_leaves=40;, score=-4087827.147 total time=   0.3s
[CV 3/3] END learning_rate=0.1, max_depth=2, n_estimators=100, num_leaves=40;, score=-4093464.858 total time=   0.3s
[CV 1/3] END learning_rate=0.1, max_depth=2, n_estimators=200, num_leaves=20;, score=-3687127.110 total time=   0.5s
[CV 2/3] END learning_rate=0.1, max_depth=2, n_estimators=200, num_leaves=20;, score=-3715787.625 total time=   0.5s
[CV 3/3] END learning_rate=0.1, max_depth=2, n_estimators=200, num_leaves=20;, score=-3678724.371 total time=   0.5s
[CV 1/3] END learning_rate=0.1, max_depth=2, n_estimators=200, n

[CV 1/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=30;, score=-2775450.352 total time=   1.8s
[CV 2/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=30;, score=-2802187.212 total time=   1.8s
[CV 3/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=30;, score=-2802288.085 total time=   1.8s
[CV 1/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=40;, score=-2775450.352 total time=   1.8s
[CV 2/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=40;, score=-2802187.212 total time=   1.5s
[CV 3/3] END learning_rate=0.1, max_depth=4, n_estimators=500, num_leaves=40;, score=-2802288.085 total time=   1.5s
[CV 1/3] END learning_rate=0.1, max_depth=5, n_estimators=100, num_leaves=20;, score=-3016529.292 total time=   0.6s
[CV 2/3] END learning_rate=0.1, max_depth=5, n_estimators=100, num_leaves=20;, score=-3036898.057 total time=   0.5s
[CV 3/3] END learning_rate=0.1, max_depth=5, n_estimators=100, n

[CV 3/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=20;, score=-3283610.220 total time=   0.5s
[CV 1/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=30;, score=-3210999.800 total time=   0.5s
[CV 2/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=30;, score=-3234970.307 total time=   0.5s
[CV 3/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=30;, score=-3283610.220 total time=   0.5s
[CV 1/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=40;, score=-3210999.800 total time=   0.5s
[CV 2/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=40;, score=-3234970.307 total time=   0.5s
[CV 3/3] END learning_rate=0.5, max_depth=2, n_estimators=200, num_leaves=40;, score=-3283610.220 total time=   0.5s
[CV 1/3] END learning_rate=0.5, max_depth=2, n_estimators=500, num_leaves=20;, score=-3008304.457 total time=   0.9s
[CV 2/3] END learning_rate=0.5, max_depth=2, n_estimators=500, n

[CV 2/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=20;, score=-2914709.978 total time=   0.4s
[CV 3/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=20;, score=-2920363.356 total time=   0.4s
[CV 1/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=30;, score=-2854058.348 total time=   0.5s
[CV 2/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=30;, score=-2894135.664 total time=   0.5s
[CV 3/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=30;, score=-2864353.256 total time=   0.5s
[CV 1/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=40;, score=-2852963.434 total time=   0.5s
[CV 2/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=40;, score=-2908322.466 total time=   0.5s
[CV 3/3] END learning_rate=0.5, max_depth=5, n_estimators=100, num_leaves=40;, score=-2864366.523 total time=   0.5s
[CV 1/3] END learning_rate=0.5, max_depth=5, n_estimators=200, n

In [58]:
print('Лучшее значение RMSE в LightGBM:', round(abs(result_lgbm.best_score_)**0.5, 2))
print('Лучшие параметры LightGBM:', result_lgbm.best_params_)
print('Время выполнения кода:', time_lgbm)

Лучшее значение RMSE в LightGBM: 1621.63
Лучшие параметры LightGBM: {'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 500, 'num_leaves': 40}
Время выполнения кода: 0:06:03.041867


Мы перебрали много параметров, каждый щаг считался достаточно быстро: 1-2 секунды, в общем выполнение кода заняло 10 минут, это хорошее время для такого количество шагов, RMSE = 1621, это почти в два раза лучше результата в линейной регрессии.

In [60]:
# Найдем время обучения и предсказания модели LightGBM
start_time = datetime.now()
best_model_lgbm = search_lgbm.best_estimator_
best_model_lgbm.fit(features_train_categorial, target_train_categorial)
end_time = datetime.now()
time_lgbm_fit = end_time - start_time

start_time = datetime.now()
predictions=best_model_lgbm.predict(features_test_categorial)
end_time = datetime.now()
time_lgbm_predict = end_time - start_time
print('Время обучения модели LightGBM:', time_lgbm_fit)
print('Время предсказания модели LightGBM:', time_lgbm_predict)

Время обучения модели LightGBM: 0:00:02.104028
Время предсказания модели LightGBM: 0:00:00.335054


### XGBoost

In [61]:
start_time = datetime.now()

model_xgb = XGBRegressor(random_state=12345)
params_xgb = {'eta' : [0.1, 0.3, 0.5],
               'max_depth' : [6]}

search_xgb = GridSearchCV(estimator=model_xgb, param_grid=params_xgb, scoring='neg_mean_squared_error',
                           verbose=5, cv=3)
result_xgb = search_xgb.fit(features_train , target_train)

end_time = datetime.now()
time_xgb = end_time - start_time

Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV 1/3] END .......eta=0.1, max_depth=6;, score=-3095642.746 total time=  47.0s
[CV 2/3] END .......eta=0.1, max_depth=6;, score=-3100871.004 total time=  51.4s
[CV 3/3] END .......eta=0.1, max_depth=6;, score=-3161173.403 total time=  52.4s
[CV 1/3] END .......eta=0.3, max_depth=6;, score=-2914307.738 total time=  52.6s
[CV 2/3] END .......eta=0.3, max_depth=6;, score=-2933719.918 total time=  52.8s
[CV 3/3] END .......eta=0.3, max_depth=6;, score=-2934120.638 total time=  51.8s
[CV 1/3] END .......eta=0.5, max_depth=6;, score=-2896571.330 total time=  52.4s
[CV 2/3] END .......eta=0.5, max_depth=6;, score=-2900111.531 total time=  53.3s
[CV 3/3] END .......eta=0.5, max_depth=6;, score=-2914440.172 total time=  54.4s


In [62]:
print('Лучшее значение RMSE в XGBoost:', round(abs(result_xgb.best_score_)**0.5, 2))
print('Лучшие параметры XGBoost:', result_xgb.best_params_)
print('Время выполнения кода:', time_xgb)

Лучшее значение RMSE в XGBoost: 1704.03
Лучшие параметры XGBoost: {'eta': 0.5, 'max_depth': 6}
Время выполнения кода: 0:09:08.699186


Сделали всего 9 шагов, и каждый шаг занял около 53 секунд, это намного дольше чем в LightGBM, однако RMSE = 1704, что близко к результату lightGBM, но все же чуть больше.

In [76]:
# Найдем время обучения и предсказания модели XGBoost
start_time = datetime.now()
best_model_xbg = search_xgb.best_estimator_
best_model_xbg.fit(features_train, target_train)
end_time = datetime.now()
time_xgb_fit = end_time - start_time

start_time = datetime.now()
predictions=best_model_xbg.predict(features_test)
end_time = datetime.now()
time_xgb_predict = end_time - start_time
print('Время обучения модели XGBoost:', time_xgb_fit)
print('Время предсказания модели XGBoost:', time_xgb_predict)

Время обучения модели XGBoost: 0:01:08.542189
Время предсказания модели XGBoost: 0:00:00.261927


### CatBoost

In [66]:
start_time = datetime.now()

model_cat = CatBoostRegressor(random_seed=12345)
params_cat = {'iterations' : [100, 300, 500],
              'depth' : range(4, 8),
              'grow_policy' : ['SymmetricTree']}

search_cat = GridSearchCV(estimator=model_cat, param_grid=params_cat, scoring='neg_mean_squared_error',
                           verbose=1, cv=3)
result_cat = search_cat.fit(features_train, target_train)

end_time = datetime.now()
time_cat = end_time - start_time

Fitting 3 folds for each of 12 candidates, totalling 36 fits
Learning rate set to 0.5
0:	learn: 3440.5774848	total: 69.7ms	remaining: 6.89s
1:	learn: 2844.9246012	total: 76.2ms	remaining: 3.73s
2:	learn: 2576.5544905	total: 81.4ms	remaining: 2.63s
3:	learn: 2436.5221506	total: 88.2ms	remaining: 2.12s
4:	learn: 2333.1243026	total: 94.4ms	remaining: 1.79s
5:	learn: 2275.8465628	total: 101ms	remaining: 1.58s
6:	learn: 2228.9726571	total: 107ms	remaining: 1.42s
7:	learn: 2198.6819355	total: 113ms	remaining: 1.3s
8:	learn: 2166.5171045	total: 120ms	remaining: 1.21s
9:	learn: 2144.2111543	total: 126ms	remaining: 1.14s
10:	learn: 2121.6614146	total: 133ms	remaining: 1.08s
11:	learn: 2104.7949414	total: 139ms	remaining: 1.02s
12:	learn: 2085.3522676	total: 146ms	remaining: 975ms
13:	learn: 2071.1068809	total: 152ms	remaining: 932ms
14:	learn: 2060.8471252	total: 158ms	remaining: 896ms
15:	learn: 2047.2850893	total: 166ms	remaining: 870ms
16:	learn: 2040.2451523	total: 172ms	remaining: 842ms
17

54:	learn: 1870.1565803	total: 365ms	remaining: 299ms
55:	learn: 1868.1433421	total: 373ms	remaining: 293ms
56:	learn: 1865.2717731	total: 381ms	remaining: 287ms
57:	learn: 1862.3574134	total: 388ms	remaining: 281ms
58:	learn: 1860.8123338	total: 394ms	remaining: 274ms
59:	learn: 1858.9633183	total: 402ms	remaining: 268ms
60:	learn: 1856.0396346	total: 409ms	remaining: 261ms
61:	learn: 1853.8556123	total: 416ms	remaining: 255ms
62:	learn: 1851.9447916	total: 422ms	remaining: 248ms
63:	learn: 1850.0309763	total: 429ms	remaining: 241ms
64:	learn: 1846.3095489	total: 436ms	remaining: 235ms
65:	learn: 1843.6805641	total: 442ms	remaining: 228ms
66:	learn: 1841.4108696	total: 448ms	remaining: 221ms
67:	learn: 1839.6475674	total: 454ms	remaining: 214ms
68:	learn: 1836.2791890	total: 461ms	remaining: 207ms
69:	learn: 1834.2232005	total: 467ms	remaining: 200ms
70:	learn: 1832.0162287	total: 473ms	remaining: 193ms
71:	learn: 1828.4517313	total: 480ms	remaining: 187ms
72:	learn: 1826.8378479	tota

21:	learn: 2122.3149933	total: 163ms	remaining: 2.06s
22:	learn: 2112.3671481	total: 170ms	remaining: 2.05s
23:	learn: 2104.6201410	total: 177ms	remaining: 2.04s
24:	learn: 2096.1966425	total: 184ms	remaining: 2.02s
25:	learn: 2088.9354818	total: 190ms	remaining: 2s
26:	learn: 2078.3501527	total: 197ms	remaining: 1.99s
27:	learn: 2071.1675000	total: 203ms	remaining: 1.97s
28:	learn: 2063.0064323	total: 209ms	remaining: 1.96s
29:	learn: 2054.5066662	total: 216ms	remaining: 1.95s
30:	learn: 2049.2070154	total: 222ms	remaining: 1.93s
31:	learn: 2041.3159723	total: 229ms	remaining: 1.92s
32:	learn: 2033.0237047	total: 235ms	remaining: 1.91s
33:	learn: 2028.2307470	total: 242ms	remaining: 1.89s
34:	learn: 2024.3096918	total: 248ms	remaining: 1.88s
35:	learn: 2016.4475373	total: 254ms	remaining: 1.86s
36:	learn: 2009.3309098	total: 261ms	remaining: 1.85s
37:	learn: 2004.1088317	total: 267ms	remaining: 1.84s
38:	learn: 1998.5340115	total: 273ms	remaining: 1.83s
39:	learn: 1995.0253821	total: 

172:	learn: 1784.6854924	total: 1.15s	remaining: 846ms
173:	learn: 1783.9859172	total: 1.16s	remaining: 841ms
174:	learn: 1783.4259378	total: 1.17s	remaining: 835ms
175:	learn: 1783.1209078	total: 1.18s	remaining: 830ms
176:	learn: 1782.3237163	total: 1.19s	remaining: 825ms
177:	learn: 1781.6380875	total: 1.2s	remaining: 820ms
178:	learn: 1781.0037546	total: 1.21s	remaining: 816ms
179:	learn: 1780.1034142	total: 1.22s	remaining: 811ms
180:	learn: 1779.4651257	total: 1.23s	remaining: 808ms
181:	learn: 1778.7618886	total: 1.25s	remaining: 812ms
182:	learn: 1777.7408214	total: 1.27s	remaining: 815ms
183:	learn: 1776.3890109	total: 1.28s	remaining: 807ms
184:	learn: 1775.9017926	total: 1.29s	remaining: 800ms
185:	learn: 1775.4483734	total: 1.29s	remaining: 793ms
186:	learn: 1774.9094093	total: 1.3s	remaining: 785ms
187:	learn: 1774.3435804	total: 1.3s	remaining: 778ms
188:	learn: 1773.7670354	total: 1.31s	remaining: 770ms
189:	learn: 1772.8520317	total: 1.32s	remaining: 763ms
190:	learn: 1

25:	learn: 2083.4366210	total: 168ms	remaining: 1.77s
26:	learn: 2072.0405813	total: 174ms	remaining: 1.76s
27:	learn: 2064.0282416	total: 182ms	remaining: 1.76s
28:	learn: 2056.4558222	total: 188ms	remaining: 1.75s
29:	learn: 2049.0610118	total: 194ms	remaining: 1.75s
30:	learn: 2043.0038576	total: 200ms	remaining: 1.74s
31:	learn: 2037.9096087	total: 207ms	remaining: 1.73s
32:	learn: 2033.2927835	total: 213ms	remaining: 1.72s
33:	learn: 2023.6718922	total: 220ms	remaining: 1.72s
34:	learn: 2019.3899960	total: 226ms	remaining: 1.71s
35:	learn: 2015.3862226	total: 232ms	remaining: 1.7s
36:	learn: 2007.6836356	total: 238ms	remaining: 1.69s
37:	learn: 2001.9756165	total: 244ms	remaining: 1.68s
38:	learn: 1996.2322493	total: 251ms	remaining: 1.68s
39:	learn: 1991.7527300	total: 257ms	remaining: 1.67s
40:	learn: 1987.5560077	total: 263ms	remaining: 1.66s
41:	learn: 1982.7144546	total: 270ms	remaining: 1.66s
42:	learn: 1979.1584219	total: 276ms	remaining: 1.65s
43:	learn: 1976.6710338	total

183:	learn: 1779.2572155	total: 1.17s	remaining: 735ms
184:	learn: 1778.7259773	total: 1.17s	remaining: 728ms
185:	learn: 1778.2916413	total: 1.18s	remaining: 723ms
186:	learn: 1777.8134756	total: 1.19s	remaining: 717ms
187:	learn: 1777.4470661	total: 1.19s	remaining: 710ms
188:	learn: 1777.0487404	total: 1.2s	remaining: 704ms
189:	learn: 1776.3742441	total: 1.2s	remaining: 697ms
190:	learn: 1775.8194209	total: 1.21s	remaining: 691ms
191:	learn: 1775.2473087	total: 1.22s	remaining: 684ms
192:	learn: 1774.7005469	total: 1.22s	remaining: 678ms
193:	learn: 1773.5626763	total: 1.23s	remaining: 672ms
194:	learn: 1772.3884804	total: 1.24s	remaining: 666ms
195:	learn: 1772.0171196	total: 1.24s	remaining: 659ms
196:	learn: 1771.3025311	total: 1.25s	remaining: 653ms
197:	learn: 1770.9282998	total: 1.25s	remaining: 646ms
198:	learn: 1770.4705341	total: 1.26s	remaining: 640ms
199:	learn: 1769.6480389	total: 1.27s	remaining: 633ms
200:	learn: 1768.8670802	total: 1.27s	remaining: 627ms
201:	learn: 

53:	learn: 1933.4547184	total: 360ms	remaining: 1.64s
54:	learn: 1930.0117841	total: 368ms	remaining: 1.64s
55:	learn: 1928.4186396	total: 375ms	remaining: 1.64s
56:	learn: 1924.0300816	total: 383ms	remaining: 1.63s
57:	learn: 1921.1499030	total: 392ms	remaining: 1.63s
58:	learn: 1918.1672585	total: 400ms	remaining: 1.63s
59:	learn: 1914.8127887	total: 408ms	remaining: 1.63s
60:	learn: 1912.9462885	total: 415ms	remaining: 1.62s
61:	learn: 1911.4912660	total: 422ms	remaining: 1.62s
62:	learn: 1909.2193719	total: 429ms	remaining: 1.61s
63:	learn: 1907.4333666	total: 437ms	remaining: 1.61s
64:	learn: 1905.1956024	total: 444ms	remaining: 1.61s
65:	learn: 1902.4864187	total: 452ms	remaining: 1.6s
66:	learn: 1900.1152894	total: 459ms	remaining: 1.6s
67:	learn: 1897.9950717	total: 465ms	remaining: 1.59s
68:	learn: 1896.1374350	total: 473ms	remaining: 1.58s
69:	learn: 1894.1641449	total: 479ms	remaining: 1.57s
70:	learn: 1891.9632613	total: 486ms	remaining: 1.57s
71:	learn: 1889.2019356	total:

206:	learn: 1760.8462556	total: 1.36s	remaining: 610ms
207:	learn: 1760.4929162	total: 1.36s	remaining: 603ms
208:	learn: 1759.9927971	total: 1.37s	remaining: 597ms
209:	learn: 1759.3929278	total: 1.38s	remaining: 591ms
210:	learn: 1758.9060716	total: 1.38s	remaining: 584ms
211:	learn: 1757.9327247	total: 1.39s	remaining: 577ms
212:	learn: 1757.7258451	total: 1.4s	remaining: 570ms
213:	learn: 1757.4403292	total: 1.4s	remaining: 564ms
214:	learn: 1757.0044918	total: 1.41s	remaining: 557ms
215:	learn: 1756.2208682	total: 1.42s	remaining: 550ms
216:	learn: 1755.8320120	total: 1.42s	remaining: 544ms
217:	learn: 1755.4644776	total: 1.43s	remaining: 537ms
218:	learn: 1754.9669371	total: 1.43s	remaining: 530ms
219:	learn: 1754.4532968	total: 1.44s	remaining: 524ms
220:	learn: 1753.8406540	total: 1.45s	remaining: 517ms
221:	learn: 1753.2946856	total: 1.45s	remaining: 511ms
222:	learn: 1752.9399705	total: 1.46s	remaining: 504ms
223:	learn: 1752.3773056	total: 1.47s	remaining: 498ms
224:	learn: 

84:	learn: 1930.3340850	total: 564ms	remaining: 2.75s
85:	learn: 1927.9581231	total: 571ms	remaining: 2.75s
86:	learn: 1926.6477965	total: 578ms	remaining: 2.74s
87:	learn: 1924.5882192	total: 585ms	remaining: 2.74s
88:	learn: 1922.3977688	total: 591ms	remaining: 2.73s
89:	learn: 1920.4594091	total: 598ms	remaining: 2.72s
90:	learn: 1919.2432237	total: 605ms	remaining: 2.72s
91:	learn: 1918.2828371	total: 611ms	remaining: 2.71s
92:	learn: 1917.3535834	total: 617ms	remaining: 2.7s
93:	learn: 1915.3210105	total: 623ms	remaining: 2.69s
94:	learn: 1914.4445045	total: 630ms	remaining: 2.68s
95:	learn: 1912.6941943	total: 636ms	remaining: 2.68s
96:	learn: 1911.4313001	total: 643ms	remaining: 2.67s
97:	learn: 1910.1950268	total: 649ms	remaining: 2.66s
98:	learn: 1908.0065623	total: 656ms	remaining: 2.66s
99:	learn: 1906.4183506	total: 662ms	remaining: 2.65s
100:	learn: 1904.8597588	total: 669ms	remaining: 2.64s
101:	learn: 1903.6798074	total: 675ms	remaining: 2.63s
102:	learn: 1902.3667502	to

242:	learn: 1793.7420408	total: 1.57s	remaining: 1.66s
243:	learn: 1793.2367182	total: 1.57s	remaining: 1.65s
244:	learn: 1792.7672455	total: 1.58s	remaining: 1.65s
245:	learn: 1792.5029813	total: 1.59s	remaining: 1.64s
246:	learn: 1791.8341089	total: 1.59s	remaining: 1.63s
247:	learn: 1791.3149099	total: 1.6s	remaining: 1.63s
248:	learn: 1790.8648854	total: 1.61s	remaining: 1.62s
249:	learn: 1789.8965314	total: 1.61s	remaining: 1.61s
250:	learn: 1789.4152113	total: 1.62s	remaining: 1.61s
251:	learn: 1788.8726361	total: 1.63s	remaining: 1.6s
252:	learn: 1788.5873048	total: 1.63s	remaining: 1.59s
253:	learn: 1788.2913717	total: 1.64s	remaining: 1.59s
254:	learn: 1787.9010153	total: 1.65s	remaining: 1.58s
255:	learn: 1787.3941523	total: 1.65s	remaining: 1.57s
256:	learn: 1786.9646380	total: 1.66s	remaining: 1.57s
257:	learn: 1786.3949846	total: 1.66s	remaining: 1.56s
258:	learn: 1785.7946180	total: 1.67s	remaining: 1.55s
259:	learn: 1785.3808383	total: 1.68s	remaining: 1.55s
260:	learn: 

394:	learn: 1737.7335536	total: 2.56s	remaining: 682ms
395:	learn: 1737.5773465	total: 2.57s	remaining: 675ms
396:	learn: 1737.1891063	total: 2.58s	remaining: 669ms
397:	learn: 1736.9606476	total: 2.59s	remaining: 663ms
398:	learn: 1736.8045120	total: 2.59s	remaining: 656ms
399:	learn: 1736.4626587	total: 2.6s	remaining: 650ms
400:	learn: 1735.9385362	total: 2.6s	remaining: 643ms
401:	learn: 1735.5624130	total: 2.61s	remaining: 637ms
402:	learn: 1735.2971052	total: 2.62s	remaining: 630ms
403:	learn: 1735.0600763	total: 2.62s	remaining: 624ms
404:	learn: 1734.8891504	total: 2.63s	remaining: 617ms
405:	learn: 1734.6390699	total: 2.64s	remaining: 611ms
406:	learn: 1734.4511972	total: 2.64s	remaining: 604ms
407:	learn: 1734.2291382	total: 2.65s	remaining: 598ms
408:	learn: 1734.0437682	total: 2.66s	remaining: 591ms
409:	learn: 1733.8201549	total: 2.66s	remaining: 584ms
410:	learn: 1733.6068583	total: 2.67s	remaining: 578ms
411:	learn: 1733.4401361	total: 2.67s	remaining: 571ms
412:	learn: 

56:	learn: 2000.1342931	total: 366ms	remaining: 2.85s
57:	learn: 1996.0424263	total: 372ms	remaining: 2.84s
58:	learn: 1993.5336987	total: 379ms	remaining: 2.83s
59:	learn: 1989.4363256	total: 386ms	remaining: 2.83s
60:	learn: 1984.7755894	total: 392ms	remaining: 2.82s
61:	learn: 1982.5929869	total: 398ms	remaining: 2.81s
62:	learn: 1981.0154261	total: 405ms	remaining: 2.81s
63:	learn: 1979.0908203	total: 411ms	remaining: 2.8s
64:	learn: 1976.9551961	total: 418ms	remaining: 2.79s
65:	learn: 1974.9143541	total: 424ms	remaining: 2.79s
66:	learn: 1971.2760472	total: 430ms	remaining: 2.78s
67:	learn: 1968.7349058	total: 436ms	remaining: 2.77s
68:	learn: 1966.8772649	total: 442ms	remaining: 2.76s
69:	learn: 1963.0695134	total: 449ms	remaining: 2.76s
70:	learn: 1960.6074822	total: 455ms	remaining: 2.75s
71:	learn: 1958.9519110	total: 461ms	remaining: 2.74s
72:	learn: 1957.5263297	total: 467ms	remaining: 2.73s
73:	learn: 1956.2407261	total: 473ms	remaining: 2.73s
74:	learn: 1954.4982731	total

211:	learn: 1803.1225395	total: 1.37s	remaining: 1.86s
212:	learn: 1802.7804371	total: 1.38s	remaining: 1.85s
213:	learn: 1802.2431906	total: 1.38s	remaining: 1.85s
214:	learn: 1801.9343149	total: 1.39s	remaining: 1.84s
215:	learn: 1801.6822704	total: 1.39s	remaining: 1.83s
216:	learn: 1801.3892174	total: 1.4s	remaining: 1.83s
217:	learn: 1800.6803356	total: 1.41s	remaining: 1.82s
218:	learn: 1799.8541393	total: 1.41s	remaining: 1.81s
219:	learn: 1799.4426888	total: 1.42s	remaining: 1.81s
220:	learn: 1798.9988835	total: 1.43s	remaining: 1.8s
221:	learn: 1798.4115842	total: 1.43s	remaining: 1.79s
222:	learn: 1797.7439933	total: 1.44s	remaining: 1.79s
223:	learn: 1797.2425920	total: 1.45s	remaining: 1.78s
224:	learn: 1796.5141534	total: 1.45s	remaining: 1.77s
225:	learn: 1796.0873385	total: 1.46s	remaining: 1.77s
226:	learn: 1795.4642970	total: 1.47s	remaining: 1.76s
227:	learn: 1794.8798213	total: 1.47s	remaining: 1.76s
228:	learn: 1794.4830641	total: 1.48s	remaining: 1.75s
229:	learn: 

361:	learn: 1744.4459552	total: 2.36s	remaining: 900ms
362:	learn: 1744.0304715	total: 2.37s	remaining: 894ms
363:	learn: 1743.7558714	total: 2.37s	remaining: 887ms
364:	learn: 1743.3917296	total: 2.38s	remaining: 881ms
365:	learn: 1743.0911014	total: 2.39s	remaining: 874ms
366:	learn: 1742.7863265	total: 2.39s	remaining: 868ms
367:	learn: 1742.2813488	total: 2.4s	remaining: 861ms
368:	learn: 1742.0565462	total: 2.41s	remaining: 855ms
369:	learn: 1741.8181649	total: 2.41s	remaining: 848ms
370:	learn: 1741.5106044	total: 2.42s	remaining: 841ms
371:	learn: 1741.2331956	total: 2.43s	remaining: 835ms
372:	learn: 1740.9680371	total: 2.43s	remaining: 828ms
373:	learn: 1740.8714991	total: 2.44s	remaining: 822ms
374:	learn: 1740.6290556	total: 2.44s	remaining: 815ms
375:	learn: 1740.3170014	total: 2.45s	remaining: 808ms
376:	learn: 1740.0634147	total: 2.46s	remaining: 802ms
377:	learn: 1739.9064787	total: 2.46s	remaining: 795ms
378:	learn: 1739.5223891	total: 2.47s	remaining: 789ms
379:	learn:

24:	learn: 2185.6512855	total: 166ms	remaining: 3.15s
25:	learn: 2174.0322067	total: 173ms	remaining: 3.16s
26:	learn: 2164.9335140	total: 181ms	remaining: 3.17s
27:	learn: 2154.9020993	total: 187ms	remaining: 3.16s
28:	learn: 2145.2480118	total: 194ms	remaining: 3.16s
29:	learn: 2135.6485606	total: 201ms	remaining: 3.15s
30:	learn: 2126.5791125	total: 208ms	remaining: 3.14s
31:	learn: 2117.6221302	total: 214ms	remaining: 3.14s
32:	learn: 2106.7299464	total: 221ms	remaining: 3.13s
33:	learn: 2097.7450581	total: 228ms	remaining: 3.12s
34:	learn: 2087.7811340	total: 235ms	remaining: 3.12s
35:	learn: 2081.7626201	total: 241ms	remaining: 3.11s
36:	learn: 2073.1895213	total: 248ms	remaining: 3.1s
37:	learn: 2068.3312464	total: 254ms	remaining: 3.09s
38:	learn: 2063.2595705	total: 261ms	remaining: 3.08s
39:	learn: 2058.9700912	total: 267ms	remaining: 3.07s
40:	learn: 2052.8742027	total: 275ms	remaining: 3.07s
41:	learn: 2048.1564126	total: 281ms	remaining: 3.06s
42:	learn: 2042.8003428	total

175:	learn: 1816.0835430	total: 1.16s	remaining: 2.14s
176:	learn: 1815.2747976	total: 1.17s	remaining: 2.13s
177:	learn: 1814.6078277	total: 1.18s	remaining: 2.13s
178:	learn: 1813.7607023	total: 1.18s	remaining: 2.12s
179:	learn: 1813.0239964	total: 1.19s	remaining: 2.12s
180:	learn: 1812.4043200	total: 1.2s	remaining: 2.11s
181:	learn: 1811.2829209	total: 1.2s	remaining: 2.1s
182:	learn: 1810.5091982	total: 1.21s	remaining: 2.1s
183:	learn: 1809.7823808	total: 1.22s	remaining: 2.09s
184:	learn: 1808.7166273	total: 1.22s	remaining: 2.08s
185:	learn: 1808.2696093	total: 1.23s	remaining: 2.08s
186:	learn: 1807.9513215	total: 1.24s	remaining: 2.07s
187:	learn: 1807.3068975	total: 1.24s	remaining: 2.06s
188:	learn: 1806.9851084	total: 1.25s	remaining: 2.05s
189:	learn: 1806.3664718	total: 1.25s	remaining: 2.05s
190:	learn: 1806.0499020	total: 1.26s	remaining: 2.04s
191:	learn: 1805.6506319	total: 1.27s	remaining: 2.03s
192:	learn: 1805.1641824	total: 1.27s	remaining: 2.02s
193:	learn: 18

325:	learn: 1747.7610600	total: 2.16s	remaining: 1.16s
326:	learn: 1747.2658450	total: 2.17s	remaining: 1.15s
327:	learn: 1747.0135107	total: 2.18s	remaining: 1.14s
328:	learn: 1746.5878976	total: 2.19s	remaining: 1.14s
329:	learn: 1746.1221425	total: 2.19s	remaining: 1.13s
330:	learn: 1745.7140282	total: 2.2s	remaining: 1.12s
331:	learn: 1745.4538919	total: 2.21s	remaining: 1.12s
332:	learn: 1745.0260474	total: 2.21s	remaining: 1.11s
333:	learn: 1744.6895951	total: 2.22s	remaining: 1.1s
334:	learn: 1744.6159224	total: 2.23s	remaining: 1.1s
335:	learn: 1744.3662667	total: 2.23s	remaining: 1.09s
336:	learn: 1744.1608618	total: 2.24s	remaining: 1.08s
337:	learn: 1743.8935096	total: 2.25s	remaining: 1.08s
338:	learn: 1743.6319216	total: 2.25s	remaining: 1.07s
339:	learn: 1743.3082393	total: 2.26s	remaining: 1.06s
340:	learn: 1743.1262247	total: 2.27s	remaining: 1.06s
341:	learn: 1742.7945035	total: 2.27s	remaining: 1.05s
342:	learn: 1742.5016891	total: 2.28s	remaining: 1.04s
343:	learn: 1

480:	learn: 1706.4812424	total: 3.16s	remaining: 125ms
481:	learn: 1706.3255685	total: 3.16s	remaining: 118ms
482:	learn: 1706.1133046	total: 3.17s	remaining: 112ms
483:	learn: 1705.9165053	total: 3.18s	remaining: 105ms
484:	learn: 1705.8529927	total: 3.18s	remaining: 98.4ms
485:	learn: 1705.7090569	total: 3.19s	remaining: 91.9ms
486:	learn: 1705.5038525	total: 3.19s	remaining: 85.3ms
487:	learn: 1705.3532901	total: 3.2s	remaining: 78.7ms
488:	learn: 1705.1599845	total: 3.21s	remaining: 72.2ms
489:	learn: 1704.9954917	total: 3.22s	remaining: 65.6ms
490:	learn: 1704.7147150	total: 3.22s	remaining: 59.1ms
491:	learn: 1704.5307230	total: 3.23s	remaining: 52.5ms
492:	learn: 1704.3305447	total: 3.23s	remaining: 45.9ms
493:	learn: 1704.1022950	total: 3.24s	remaining: 39.4ms
494:	learn: 1703.8806505	total: 3.25s	remaining: 32.8ms
495:	learn: 1703.6644110	total: 3.25s	remaining: 26.2ms
496:	learn: 1703.4799175	total: 3.26s	remaining: 19.7ms
497:	learn: 1703.2891564	total: 3.27s	remaining: 13.1

51:	learn: 1822.2788011	total: 364ms	remaining: 336ms
52:	learn: 1819.3498455	total: 372ms	remaining: 329ms
53:	learn: 1818.0827395	total: 379ms	remaining: 323ms
54:	learn: 1816.2221275	total: 387ms	remaining: 316ms
55:	learn: 1813.8965597	total: 394ms	remaining: 309ms
56:	learn: 1811.2428264	total: 401ms	remaining: 302ms
57:	learn: 1809.9003836	total: 407ms	remaining: 295ms
58:	learn: 1808.3925298	total: 414ms	remaining: 288ms
59:	learn: 1806.0484982	total: 421ms	remaining: 281ms
60:	learn: 1803.5567409	total: 429ms	remaining: 274ms
61:	learn: 1799.8504830	total: 436ms	remaining: 267ms
62:	learn: 1796.1168109	total: 443ms	remaining: 260ms
63:	learn: 1794.9406403	total: 450ms	remaining: 253ms
64:	learn: 1792.4136338	total: 456ms	remaining: 246ms
65:	learn: 1790.5846980	total: 463ms	remaining: 239ms
66:	learn: 1789.6999563	total: 470ms	remaining: 232ms
67:	learn: 1787.1559791	total: 477ms	remaining: 224ms
68:	learn: 1784.2204786	total: 484ms	remaining: 217ms
69:	learn: 1781.0001398	tota

19:	learn: 2063.2797301	total: 166ms	remaining: 2.32s
20:	learn: 2046.6483532	total: 174ms	remaining: 2.32s
21:	learn: 2036.8256434	total: 183ms	remaining: 2.31s
22:	learn: 2026.4584084	total: 191ms	remaining: 2.3s
23:	learn: 2016.8194448	total: 200ms	remaining: 2.3s
24:	learn: 2009.4067227	total: 208ms	remaining: 2.29s
25:	learn: 2000.7970755	total: 217ms	remaining: 2.28s
26:	learn: 1995.2808640	total: 225ms	remaining: 2.27s
27:	learn: 1988.5219933	total: 233ms	remaining: 2.27s
28:	learn: 1982.8426471	total: 241ms	remaining: 2.25s
29:	learn: 1975.8319545	total: 250ms	remaining: 2.25s
30:	learn: 1970.9757973	total: 258ms	remaining: 2.24s
31:	learn: 1966.2499453	total: 267ms	remaining: 2.24s
32:	learn: 1961.6241021	total: 277ms	remaining: 2.24s
33:	learn: 1956.4958294	total: 285ms	remaining: 2.23s
34:	learn: 1949.3297858	total: 294ms	remaining: 2.23s
35:	learn: 1940.5678504	total: 302ms	remaining: 2.22s
36:	learn: 1937.0543869	total: 311ms	remaining: 2.21s
37:	learn: 1932.5112350	total:

174:	learn: 1735.2201987	total: 1.35s	remaining: 964ms
175:	learn: 1734.2111507	total: 1.36s	remaining: 956ms
176:	learn: 1733.6922385	total: 1.36s	remaining: 948ms
177:	learn: 1733.3114849	total: 1.37s	remaining: 941ms
178:	learn: 1732.8103894	total: 1.38s	remaining: 932ms
179:	learn: 1732.1247330	total: 1.39s	remaining: 924ms
180:	learn: 1731.7425074	total: 1.39s	remaining: 916ms
181:	learn: 1731.2536112	total: 1.4s	remaining: 908ms
182:	learn: 1730.6128958	total: 1.41s	remaining: 900ms
183:	learn: 1730.1298699	total: 1.41s	remaining: 891ms
184:	learn: 1729.4825854	total: 1.42s	remaining: 883ms
185:	learn: 1728.8569209	total: 1.43s	remaining: 875ms
186:	learn: 1727.9568866	total: 1.43s	remaining: 867ms
187:	learn: 1727.2959072	total: 1.44s	remaining: 859ms
188:	learn: 1726.7477869	total: 1.45s	remaining: 851ms
189:	learn: 1725.8333069	total: 1.46s	remaining: 843ms
190:	learn: 1724.6152384	total: 1.46s	remaining: 835ms
191:	learn: 1723.9395817	total: 1.47s	remaining: 828ms
192:	learn:

48:	learn: 1905.1098934	total: 372ms	remaining: 1.91s
49:	learn: 1901.6372697	total: 380ms	remaining: 1.9s
50:	learn: 1898.8106876	total: 388ms	remaining: 1.89s
51:	learn: 1896.4690226	total: 395ms	remaining: 1.88s
52:	learn: 1895.0485012	total: 402ms	remaining: 1.87s
53:	learn: 1890.9139936	total: 410ms	remaining: 1.87s
54:	learn: 1887.7896710	total: 417ms	remaining: 1.86s
55:	learn: 1883.8399882	total: 425ms	remaining: 1.85s
56:	learn: 1881.7909343	total: 434ms	remaining: 1.85s
57:	learn: 1880.0891104	total: 441ms	remaining: 1.84s
58:	learn: 1878.4456729	total: 450ms	remaining: 1.84s
59:	learn: 1875.3037158	total: 458ms	remaining: 1.83s
60:	learn: 1872.1541976	total: 466ms	remaining: 1.82s
61:	learn: 1869.9937502	total: 474ms	remaining: 1.82s
62:	learn: 1867.8643209	total: 483ms	remaining: 1.81s
63:	learn: 1865.9274882	total: 491ms	remaining: 1.81s
64:	learn: 1864.0954320	total: 499ms	remaining: 1.8s
65:	learn: 1862.1108229	total: 507ms	remaining: 1.8s
66:	learn: 1860.8991872	total: 

211:	learn: 1712.4970112	total: 1.57s	remaining: 651ms
212:	learn: 1712.0601834	total: 1.58s	remaining: 644ms
213:	learn: 1711.5978869	total: 1.58s	remaining: 637ms
214:	learn: 1711.2018424	total: 1.59s	remaining: 630ms
215:	learn: 1710.7200040	total: 1.6s	remaining: 622ms
216:	learn: 1710.3803614	total: 1.61s	remaining: 615ms
217:	learn: 1709.7343536	total: 1.61s	remaining: 607ms
218:	learn: 1708.9306306	total: 1.62s	remaining: 600ms
219:	learn: 1708.4533463	total: 1.63s	remaining: 593ms
220:	learn: 1708.1266307	total: 1.64s	remaining: 585ms
221:	learn: 1707.5625389	total: 1.64s	remaining: 578ms
222:	learn: 1706.9534257	total: 1.65s	remaining: 570ms
223:	learn: 1706.6085248	total: 1.66s	remaining: 563ms
224:	learn: 1706.0895815	total: 1.67s	remaining: 556ms
225:	learn: 1705.5376855	total: 1.67s	remaining: 548ms
226:	learn: 1704.7028408	total: 1.68s	remaining: 541ms
227:	learn: 1704.2986663	total: 1.69s	remaining: 533ms
228:	learn: 1703.3755734	total: 1.7s	remaining: 526ms
229:	learn: 

81:	learn: 1820.8133147	total: 574ms	remaining: 1.53s
82:	learn: 1819.5599363	total: 581ms	remaining: 1.52s
83:	learn: 1818.5858894	total: 589ms	remaining: 1.51s
84:	learn: 1817.1362075	total: 596ms	remaining: 1.51s
85:	learn: 1815.6543831	total: 603ms	remaining: 1.5s
86:	learn: 1814.8087347	total: 610ms	remaining: 1.49s
87:	learn: 1813.5181575	total: 617ms	remaining: 1.49s
88:	learn: 1812.6138507	total: 624ms	remaining: 1.48s
89:	learn: 1811.3844757	total: 631ms	remaining: 1.47s
90:	learn: 1809.8127080	total: 638ms	remaining: 1.46s
91:	learn: 1808.7589014	total: 645ms	remaining: 1.46s
92:	learn: 1807.8405853	total: 652ms	remaining: 1.45s
93:	learn: 1806.8887668	total: 658ms	remaining: 1.44s
94:	learn: 1805.8840423	total: 665ms	remaining: 1.44s
95:	learn: 1804.6892166	total: 672ms	remaining: 1.43s
96:	learn: 1803.5224501	total: 679ms	remaining: 1.42s
97:	learn: 1801.1683057	total: 686ms	remaining: 1.41s
98:	learn: 1800.3184200	total: 693ms	remaining: 1.41s
99:	learn: 1798.8832721	total

254:	learn: 1687.8764084	total: 1.78s	remaining: 315ms
255:	learn: 1687.5179914	total: 1.79s	remaining: 308ms
256:	learn: 1687.0722922	total: 1.8s	remaining: 301ms
257:	learn: 1686.7338515	total: 1.81s	remaining: 294ms
258:	learn: 1686.3910089	total: 1.81s	remaining: 287ms
259:	learn: 1686.1003625	total: 1.82s	remaining: 280ms
260:	learn: 1685.5105346	total: 1.83s	remaining: 273ms
261:	learn: 1685.1498777	total: 1.83s	remaining: 266ms
262:	learn: 1684.8110656	total: 1.84s	remaining: 259ms
263:	learn: 1684.5621792	total: 1.85s	remaining: 252ms
264:	learn: 1684.4111426	total: 1.85s	remaining: 245ms
265:	learn: 1684.0589855	total: 1.86s	remaining: 238ms
266:	learn: 1683.7302652	total: 1.87s	remaining: 231ms
267:	learn: 1683.3130901	total: 1.88s	remaining: 224ms
268:	learn: 1682.9272516	total: 1.88s	remaining: 217ms
269:	learn: 1682.4708935	total: 1.89s	remaining: 210ms
270:	learn: 1681.7350204	total: 1.9s	remaining: 203ms
271:	learn: 1681.1714483	total: 1.91s	remaining: 196ms
272:	learn: 

110:	learn: 1835.0293596	total: 774ms	remaining: 2.71s
111:	learn: 1834.0291963	total: 781ms	remaining: 2.71s
112:	learn: 1833.3137348	total: 788ms	remaining: 2.7s
113:	learn: 1832.5719009	total: 796ms	remaining: 2.69s
114:	learn: 1831.6903767	total: 802ms	remaining: 2.69s
115:	learn: 1829.9802669	total: 810ms	remaining: 2.68s
116:	learn: 1828.9619089	total: 817ms	remaining: 2.67s
117:	learn: 1827.7503519	total: 823ms	remaining: 2.67s
118:	learn: 1826.6450325	total: 830ms	remaining: 2.66s
119:	learn: 1825.6467916	total: 837ms	remaining: 2.65s
120:	learn: 1824.6811043	total: 844ms	remaining: 2.64s
121:	learn: 1823.4848702	total: 851ms	remaining: 2.64s
122:	learn: 1821.8960021	total: 858ms	remaining: 2.63s
123:	learn: 1820.6200525	total: 865ms	remaining: 2.62s
124:	learn: 1819.7415906	total: 872ms	remaining: 2.62s
125:	learn: 1819.0601046	total: 879ms	remaining: 2.61s
126:	learn: 1817.0853436	total: 886ms	remaining: 2.6s
127:	learn: 1815.4686794	total: 893ms	remaining: 2.59s
128:	learn: 

284:	learn: 1720.6700381	total: 1.98s	remaining: 1.49s
285:	learn: 1720.3971772	total: 1.98s	remaining: 1.48s
286:	learn: 1719.9933053	total: 1.99s	remaining: 1.48s
287:	learn: 1719.5679511	total: 2s	remaining: 1.47s
288:	learn: 1719.2802666	total: 2.01s	remaining: 1.47s
289:	learn: 1718.9700375	total: 2.01s	remaining: 1.46s
290:	learn: 1718.6752015	total: 2.02s	remaining: 1.45s
291:	learn: 1718.3705033	total: 2.03s	remaining: 1.44s
292:	learn: 1718.0787228	total: 2.03s	remaining: 1.44s
293:	learn: 1717.7773548	total: 2.04s	remaining: 1.43s
294:	learn: 1717.1697370	total: 2.05s	remaining: 1.42s
295:	learn: 1717.0130852	total: 2.06s	remaining: 1.42s
296:	learn: 1716.6872459	total: 2.06s	remaining: 1.41s
297:	learn: 1716.2987905	total: 2.07s	remaining: 1.4s
298:	learn: 1715.8015908	total: 2.08s	remaining: 1.4s
299:	learn: 1715.4525311	total: 2.08s	remaining: 1.39s
300:	learn: 1715.1364407	total: 2.09s	remaining: 1.38s
301:	learn: 1714.8439169	total: 2.1s	remaining: 1.37s
302:	learn: 1714

458:	learn: 1668.5425649	total: 3.18s	remaining: 284ms
459:	learn: 1668.4133326	total: 3.19s	remaining: 277ms
460:	learn: 1668.1937403	total: 3.19s	remaining: 270ms
461:	learn: 1667.9470649	total: 3.2s	remaining: 263ms
462:	learn: 1667.6510587	total: 3.21s	remaining: 257ms
463:	learn: 1667.4568195	total: 3.22s	remaining: 250ms
464:	learn: 1667.0369434	total: 3.22s	remaining: 243ms
465:	learn: 1666.8175370	total: 3.23s	remaining: 236ms
466:	learn: 1666.7078223	total: 3.24s	remaining: 229ms
467:	learn: 1666.4959069	total: 3.24s	remaining: 222ms
468:	learn: 1666.1875562	total: 3.25s	remaining: 215ms
469:	learn: 1665.9821354	total: 3.26s	remaining: 208ms
470:	learn: 1665.8937382	total: 3.26s	remaining: 201ms
471:	learn: 1665.6710431	total: 3.27s	remaining: 194ms
472:	learn: 1665.2782707	total: 3.28s	remaining: 187ms
473:	learn: 1665.0194626	total: 3.29s	remaining: 180ms
474:	learn: 1664.7620394	total: 3.29s	remaining: 173ms
475:	learn: 1664.6890294	total: 3.3s	remaining: 166ms
476:	learn: 

130:	learn: 1813.4813192	total: 962ms	remaining: 2.71s
131:	learn: 1812.0901874	total: 969ms	remaining: 2.7s
132:	learn: 1811.2259557	total: 977ms	remaining: 2.69s
133:	learn: 1810.1848717	total: 985ms	remaining: 2.69s
134:	learn: 1808.8768287	total: 992ms	remaining: 2.68s
135:	learn: 1807.8153883	total: 1000ms	remaining: 2.67s
136:	learn: 1807.1488998	total: 1.01s	remaining: 2.67s
137:	learn: 1806.3873577	total: 1.01s	remaining: 2.66s
138:	learn: 1804.9086852	total: 1.02s	remaining: 2.65s
139:	learn: 1803.8014069	total: 1.03s	remaining: 2.64s
140:	learn: 1802.9267105	total: 1.03s	remaining: 2.64s
141:	learn: 1801.8269186	total: 1.04s	remaining: 2.63s
142:	learn: 1801.2559086	total: 1.05s	remaining: 2.62s
143:	learn: 1800.2843200	total: 1.06s	remaining: 2.61s
144:	learn: 1799.6991668	total: 1.06s	remaining: 2.6s
145:	learn: 1798.5662196	total: 1.07s	remaining: 2.6s
146:	learn: 1797.5236797	total: 1.08s	remaining: 2.59s
147:	learn: 1797.0745026	total: 1.08s	remaining: 2.58s
148:	learn: 

297:	learn: 1716.8601637	total: 2.15s	remaining: 1.46s
298:	learn: 1716.4811895	total: 2.16s	remaining: 1.45s
299:	learn: 1716.0760250	total: 2.17s	remaining: 1.45s
300:	learn: 1715.7802477	total: 2.18s	remaining: 1.44s
301:	learn: 1715.2647841	total: 2.19s	remaining: 1.44s
302:	learn: 1714.7313609	total: 2.2s	remaining: 1.43s
303:	learn: 1714.3653921	total: 2.21s	remaining: 1.42s
304:	learn: 1714.1056734	total: 2.21s	remaining: 1.42s
305:	learn: 1713.7877774	total: 2.22s	remaining: 1.41s
306:	learn: 1713.4919141	total: 2.23s	remaining: 1.4s
307:	learn: 1713.0690378	total: 2.24s	remaining: 1.4s
308:	learn: 1712.6677576	total: 2.25s	remaining: 1.39s
309:	learn: 1711.8359871	total: 2.26s	remaining: 1.38s
310:	learn: 1711.3540509	total: 2.27s	remaining: 1.38s
311:	learn: 1711.0312921	total: 2.27s	remaining: 1.37s
312:	learn: 1710.7974374	total: 2.28s	remaining: 1.36s
313:	learn: 1710.1962412	total: 2.29s	remaining: 1.36s
314:	learn: 1709.6904141	total: 2.3s	remaining: 1.35s
315:	learn: 17

463:	learn: 1664.6646644	total: 3.35s	remaining: 260ms
464:	learn: 1664.4376630	total: 3.36s	remaining: 253ms
465:	learn: 1664.3229369	total: 3.37s	remaining: 246ms
466:	learn: 1663.9863994	total: 3.38s	remaining: 239ms
467:	learn: 1663.7507055	total: 3.38s	remaining: 231ms
468:	learn: 1663.5268244	total: 3.39s	remaining: 224ms
469:	learn: 1663.2623068	total: 3.4s	remaining: 217ms
470:	learn: 1662.9753617	total: 3.4s	remaining: 210ms
471:	learn: 1662.5729737	total: 3.41s	remaining: 202ms
472:	learn: 1662.4216903	total: 3.42s	remaining: 195ms
473:	learn: 1662.1301282	total: 3.43s	remaining: 188ms
474:	learn: 1661.7581962	total: 3.43s	remaining: 181ms
475:	learn: 1661.5743326	total: 3.44s	remaining: 173ms
476:	learn: 1661.5414076	total: 3.45s	remaining: 166ms
477:	learn: 1661.3954386	total: 3.45s	remaining: 159ms
478:	learn: 1661.1723169	total: 3.46s	remaining: 152ms
479:	learn: 1661.0449034	total: 3.47s	remaining: 144ms
480:	learn: 1660.9118471	total: 3.47s	remaining: 137ms
481:	learn: 

138:	learn: 1794.2200734	total: 969ms	remaining: 2.52s
139:	learn: 1793.6053692	total: 976ms	remaining: 2.51s
140:	learn: 1792.3967306	total: 984ms	remaining: 2.51s
141:	learn: 1791.6460007	total: 991ms	remaining: 2.5s
142:	learn: 1791.1235868	total: 998ms	remaining: 2.49s
143:	learn: 1790.2030394	total: 1s	remaining: 2.48s
144:	learn: 1789.5712041	total: 1.01s	remaining: 2.48s
145:	learn: 1788.8480960	total: 1.02s	remaining: 2.47s
146:	learn: 1788.4576063	total: 1.02s	remaining: 2.46s
147:	learn: 1787.9877639	total: 1.03s	remaining: 2.46s
148:	learn: 1787.3853552	total: 1.04s	remaining: 2.45s
149:	learn: 1786.6907378	total: 1.04s	remaining: 2.44s
150:	learn: 1786.0421326	total: 1.05s	remaining: 2.43s
151:	learn: 1785.5350890	total: 1.06s	remaining: 2.43s
152:	learn: 1784.8818743	total: 1.07s	remaining: 2.42s
153:	learn: 1783.7858654	total: 1.07s	remaining: 2.41s
154:	learn: 1782.9667768	total: 1.08s	remaining: 2.4s
155:	learn: 1782.2995682	total: 1.09s	remaining: 2.4s
156:	learn: 1781

312:	learn: 1704.2154477	total: 2.17s	remaining: 1.3s
313:	learn: 1703.9481967	total: 2.18s	remaining: 1.29s
314:	learn: 1703.6998562	total: 2.18s	remaining: 1.28s
315:	learn: 1703.3907015	total: 2.19s	remaining: 1.28s
316:	learn: 1702.8690237	total: 2.2s	remaining: 1.27s
317:	learn: 1702.4789414	total: 2.21s	remaining: 1.26s
318:	learn: 1702.1994518	total: 2.21s	remaining: 1.25s
319:	learn: 1701.9447450	total: 2.22s	remaining: 1.25s
320:	learn: 1701.7493176	total: 2.23s	remaining: 1.24s
321:	learn: 1701.4729038	total: 2.23s	remaining: 1.23s
322:	learn: 1701.3867072	total: 2.24s	remaining: 1.23s
323:	learn: 1700.9806109	total: 2.25s	remaining: 1.22s
324:	learn: 1700.5841945	total: 2.25s	remaining: 1.21s
325:	learn: 1700.2028029	total: 2.26s	remaining: 1.21s
326:	learn: 1699.7454251	total: 2.27s	remaining: 1.2s
327:	learn: 1699.4748699	total: 2.27s	remaining: 1.19s
328:	learn: 1699.2628464	total: 2.28s	remaining: 1.19s
329:	learn: 1698.8896362	total: 2.29s	remaining: 1.18s
330:	learn: 1

486:	learn: 1655.8644844	total: 3.37s	remaining: 89.9ms
487:	learn: 1655.6855034	total: 3.38s	remaining: 83ms
488:	learn: 1655.3427618	total: 3.38s	remaining: 76.1ms
489:	learn: 1655.0193157	total: 3.39s	remaining: 69.2ms
490:	learn: 1654.7695109	total: 3.4s	remaining: 62.3ms
491:	learn: 1654.5193106	total: 3.4s	remaining: 55.4ms
492:	learn: 1654.3395848	total: 3.41s	remaining: 48.4ms
493:	learn: 1654.0734891	total: 3.42s	remaining: 41.5ms
494:	learn: 1653.8973267	total: 3.42s	remaining: 34.6ms
495:	learn: 1653.6934607	total: 3.43s	remaining: 27.7ms
496:	learn: 1653.4894853	total: 3.44s	remaining: 20.8ms
497:	learn: 1653.2010278	total: 3.44s	remaining: 13.8ms
498:	learn: 1652.8143926	total: 3.45s	remaining: 6.92ms
499:	learn: 1652.5617583	total: 3.46s	remaining: 0us
Learning rate set to 0.5
0:	learn: 3286.9039589	total: 7.77ms	remaining: 769ms
1:	learn: 2708.2034843	total: 15.8ms	remaining: 775ms
2:	learn: 2426.8578979	total: 23.2ms	remaining: 751ms
3:	learn: 2281.4642031	total: 31ms	r

47:	learn: 1779.8236786	total: 372ms	remaining: 403ms
48:	learn: 1778.0220212	total: 381ms	remaining: 396ms
49:	learn: 1775.7941636	total: 389ms	remaining: 389ms
50:	learn: 1773.6993262	total: 397ms	remaining: 382ms
51:	learn: 1770.8121150	total: 405ms	remaining: 374ms
52:	learn: 1768.2734260	total: 413ms	remaining: 367ms
53:	learn: 1766.2246854	total: 421ms	remaining: 359ms
54:	learn: 1764.1869564	total: 429ms	remaining: 351ms
55:	learn: 1761.8769568	total: 436ms	remaining: 343ms
56:	learn: 1759.8428770	total: 444ms	remaining: 335ms
57:	learn: 1756.3431578	total: 453ms	remaining: 328ms
58:	learn: 1754.7645790	total: 460ms	remaining: 320ms
59:	learn: 1753.1161970	total: 468ms	remaining: 312ms
60:	learn: 1750.4777812	total: 476ms	remaining: 304ms
61:	learn: 1748.4638567	total: 484ms	remaining: 296ms
62:	learn: 1746.3834787	total: 491ms	remaining: 289ms
63:	learn: 1745.3863241	total: 499ms	remaining: 281ms
64:	learn: 1743.3008256	total: 506ms	remaining: 273ms
65:	learn: 1741.6759731	tota

99:	learn: 1691.1174966	total: 773ms	remaining: 0us
Learning rate set to 0.243349
0:	learn: 3863.2339336	total: 8.21ms	remaining: 2.45s
1:	learn: 3381.0388366	total: 16.3ms	remaining: 2.43s
2:	learn: 3044.0208815	total: 24.5ms	remaining: 2.42s
3:	learn: 2808.9871290	total: 32.4ms	remaining: 2.4s
4:	learn: 2625.0905683	total: 40.6ms	remaining: 2.4s
5:	learn: 2501.1153325	total: 48.5ms	remaining: 2.38s
6:	learn: 2399.5665489	total: 56.1ms	remaining: 2.35s
7:	learn: 2329.6313629	total: 64.2ms	remaining: 2.34s
8:	learn: 2273.0325543	total: 72ms	remaining: 2.33s
9:	learn: 2228.2883459	total: 79.6ms	remaining: 2.31s
10:	learn: 2188.1787260	total: 87.3ms	remaining: 2.29s
11:	learn: 2154.2515923	total: 95ms	remaining: 2.28s
12:	learn: 2125.6274768	total: 103ms	remaining: 2.27s
13:	learn: 2097.1045565	total: 111ms	remaining: 2.26s
14:	learn: 2077.8549734	total: 118ms	remaining: 2.24s
15:	learn: 2059.3886401	total: 126ms	remaining: 2.23s
16:	learn: 2042.0275913	total: 133ms	remaining: 2.22s
17:	

151:	learn: 1706.9274329	total: 1.17s	remaining: 1.14s
152:	learn: 1706.3041128	total: 1.18s	remaining: 1.13s
153:	learn: 1705.4732495	total: 1.19s	remaining: 1.13s
154:	learn: 1704.7896119	total: 1.19s	remaining: 1.12s
155:	learn: 1704.2647199	total: 1.2s	remaining: 1.11s
156:	learn: 1703.9750800	total: 1.21s	remaining: 1.1s
157:	learn: 1703.1274592	total: 1.22s	remaining: 1.09s
158:	learn: 1702.6928359	total: 1.22s	remaining: 1.09s
159:	learn: 1702.0090689	total: 1.23s	remaining: 1.08s
160:	learn: 1701.3448382	total: 1.24s	remaining: 1.07s
161:	learn: 1700.5386907	total: 1.25s	remaining: 1.06s
162:	learn: 1699.6333179	total: 1.26s	remaining: 1.05s
163:	learn: 1699.0437044	total: 1.26s	remaining: 1.05s
164:	learn: 1698.2001884	total: 1.27s	remaining: 1.04s
165:	learn: 1697.6206329	total: 1.28s	remaining: 1.03s
166:	learn: 1697.0104857	total: 1.29s	remaining: 1.02s
167:	learn: 1696.2868601	total: 1.29s	remaining: 1.02s
168:	learn: 1695.6445387	total: 1.3s	remaining: 1.01s
169:	learn: 1

20:	learn: 1995.6693568	total: 165ms	remaining: 2.19s
21:	learn: 1984.2795783	total: 172ms	remaining: 2.18s
22:	learn: 1975.8914897	total: 180ms	remaining: 2.17s
23:	learn: 1966.8622867	total: 189ms	remaining: 2.17s
24:	learn: 1961.3914712	total: 196ms	remaining: 2.15s
25:	learn: 1952.6150475	total: 204ms	remaining: 2.15s
26:	learn: 1947.1503679	total: 211ms	remaining: 2.14s
27:	learn: 1935.8014814	total: 219ms	remaining: 2.13s
28:	learn: 1931.2377275	total: 226ms	remaining: 2.12s
29:	learn: 1924.2122608	total: 235ms	remaining: 2.11s
30:	learn: 1918.5927449	total: 242ms	remaining: 2.1s
31:	learn: 1913.6375090	total: 250ms	remaining: 2.09s
32:	learn: 1908.8893613	total: 258ms	remaining: 2.08s
33:	learn: 1903.2192124	total: 266ms	remaining: 2.08s
34:	learn: 1895.9102937	total: 273ms	remaining: 2.07s
35:	learn: 1893.3544817	total: 280ms	remaining: 2.06s
36:	learn: 1888.5787871	total: 289ms	remaining: 2.05s
37:	learn: 1884.4632788	total: 296ms	remaining: 2.04s
38:	learn: 1881.6052765	total

176:	learn: 1689.7310378	total: 1.36s	remaining: 949ms
177:	learn: 1688.7193437	total: 1.37s	remaining: 941ms
178:	learn: 1688.0854960	total: 1.38s	remaining: 935ms
179:	learn: 1687.4309984	total: 1.39s	remaining: 927ms
180:	learn: 1686.8486194	total: 1.4s	remaining: 919ms
181:	learn: 1686.3295678	total: 1.41s	remaining: 911ms
182:	learn: 1685.7470129	total: 1.41s	remaining: 903ms
183:	learn: 1684.8681557	total: 1.42s	remaining: 895ms
184:	learn: 1684.2931976	total: 1.43s	remaining: 887ms
185:	learn: 1683.7978064	total: 1.43s	remaining: 879ms
186:	learn: 1682.8424370	total: 1.44s	remaining: 872ms
187:	learn: 1682.3827650	total: 1.45s	remaining: 864ms
188:	learn: 1681.9665170	total: 1.46s	remaining: 856ms
189:	learn: 1681.2208603	total: 1.46s	remaining: 848ms
190:	learn: 1680.7016622	total: 1.47s	remaining: 840ms
191:	learn: 1680.2621873	total: 1.48s	remaining: 833ms
192:	learn: 1679.6416171	total: 1.49s	remaining: 825ms
193:	learn: 1679.2496692	total: 1.5s	remaining: 817ms
194:	learn: 

47:	learn: 1854.3148142	total: 371ms	remaining: 1.95s
48:	learn: 1851.5246695	total: 378ms	remaining: 1.94s
49:	learn: 1849.6739186	total: 387ms	remaining: 1.93s
50:	learn: 1847.2864398	total: 394ms	remaining: 1.93s
51:	learn: 1845.4304246	total: 402ms	remaining: 1.92s
52:	learn: 1842.3330549	total: 410ms	remaining: 1.91s
53:	learn: 1840.2611378	total: 417ms	remaining: 1.9s
54:	learn: 1837.3514396	total: 425ms	remaining: 1.89s
55:	learn: 1832.5855376	total: 433ms	remaining: 1.89s
56:	learn: 1830.2349923	total: 441ms	remaining: 1.88s
57:	learn: 1827.6693796	total: 449ms	remaining: 1.87s
58:	learn: 1824.5114028	total: 456ms	remaining: 1.86s
59:	learn: 1822.1938966	total: 464ms	remaining: 1.85s
60:	learn: 1819.7998081	total: 471ms	remaining: 1.84s
61:	learn: 1815.7650136	total: 479ms	remaining: 1.84s
62:	learn: 1812.2515418	total: 487ms	remaining: 1.83s
63:	learn: 1810.1536438	total: 495ms	remaining: 1.82s
64:	learn: 1808.3426321	total: 503ms	remaining: 1.82s
65:	learn: 1806.0821783	total

203:	learn: 1666.4133323	total: 1.56s	remaining: 735ms
204:	learn: 1665.8740774	total: 1.57s	remaining: 727ms
205:	learn: 1665.3612763	total: 1.58s	remaining: 720ms
206:	learn: 1664.9480641	total: 1.58s	remaining: 712ms
207:	learn: 1664.2902966	total: 1.59s	remaining: 705ms
208:	learn: 1663.7441098	total: 1.6s	remaining: 697ms
209:	learn: 1663.4303438	total: 1.61s	remaining: 689ms
210:	learn: 1662.9555498	total: 1.61s	remaining: 681ms
211:	learn: 1662.5580136	total: 1.62s	remaining: 674ms
212:	learn: 1662.0346325	total: 1.63s	remaining: 666ms
213:	learn: 1661.5640825	total: 1.64s	remaining: 658ms
214:	learn: 1661.0161462	total: 1.65s	remaining: 651ms
215:	learn: 1660.5252066	total: 1.65s	remaining: 643ms
216:	learn: 1659.9955718	total: 1.66s	remaining: 636ms
217:	learn: 1659.1015288	total: 1.67s	remaining: 628ms
218:	learn: 1658.5639994	total: 1.68s	remaining: 620ms
219:	learn: 1658.1180215	total: 1.68s	remaining: 613ms
220:	learn: 1657.5455333	total: 1.69s	remaining: 605ms
221:	learn:

72:	learn: 1849.0728016	total: 568ms	remaining: 3.32s
73:	learn: 1847.9891318	total: 576ms	remaining: 3.31s
74:	learn: 1846.4137163	total: 584ms	remaining: 3.31s
75:	learn: 1843.8283370	total: 592ms	remaining: 3.3s
76:	learn: 1842.3268117	total: 600ms	remaining: 3.29s
77:	learn: 1839.9618642	total: 607ms	remaining: 3.29s
78:	learn: 1838.0890180	total: 615ms	remaining: 3.28s
79:	learn: 1837.1163404	total: 622ms	remaining: 3.27s
80:	learn: 1835.3240205	total: 630ms	remaining: 3.26s
81:	learn: 1834.0374067	total: 637ms	remaining: 3.25s
82:	learn: 1832.7350706	total: 645ms	remaining: 3.24s
83:	learn: 1831.0021906	total: 652ms	remaining: 3.23s
84:	learn: 1829.5443048	total: 660ms	remaining: 3.22s
85:	learn: 1828.2330206	total: 668ms	remaining: 3.21s
86:	learn: 1826.0189721	total: 676ms	remaining: 3.21s
87:	learn: 1824.9286519	total: 683ms	remaining: 3.2s
88:	learn: 1823.1415944	total: 691ms	remaining: 3.19s
89:	learn: 1821.5360160	total: 699ms	remaining: 3.19s
90:	learn: 1820.0785053	total:

228:	learn: 1702.6821294	total: 1.76s	remaining: 2.09s
229:	learn: 1701.9530689	total: 1.77s	remaining: 2.08s
230:	learn: 1701.5527261	total: 1.78s	remaining: 2.07s
231:	learn: 1700.9415110	total: 1.79s	remaining: 2.07s
232:	learn: 1700.3421379	total: 1.8s	remaining: 2.06s
233:	learn: 1699.7138597	total: 1.8s	remaining: 2.05s
234:	learn: 1699.2744008	total: 1.81s	remaining: 2.04s
235:	learn: 1699.0665664	total: 1.82s	remaining: 2.04s
236:	learn: 1698.5770580	total: 1.83s	remaining: 2.03s
237:	learn: 1698.3823490	total: 1.83s	remaining: 2.02s
238:	learn: 1697.9914962	total: 1.84s	remaining: 2.01s
239:	learn: 1697.3661327	total: 1.85s	remaining: 2s
240:	learn: 1696.9085604	total: 1.86s	remaining: 2s
241:	learn: 1696.0099895	total: 1.86s	remaining: 1.99s
242:	learn: 1695.4711254	total: 1.87s	remaining: 1.98s
243:	learn: 1695.0991047	total: 1.88s	remaining: 1.97s
244:	learn: 1694.8674644	total: 1.89s	remaining: 1.96s
245:	learn: 1694.4028037	total: 1.9s	remaining: 1.96s
246:	learn: 1694.03

384:	learn: 1642.8306402	total: 2.96s	remaining: 884ms
385:	learn: 1642.6366555	total: 2.97s	remaining: 877ms
386:	learn: 1642.5574499	total: 2.98s	remaining: 869ms
387:	learn: 1642.3542793	total: 2.98s	remaining: 862ms
388:	learn: 1642.1184683	total: 2.99s	remaining: 854ms
389:	learn: 1641.8392365	total: 3s	remaining: 846ms
390:	learn: 1641.6175090	total: 3.01s	remaining: 838ms
391:	learn: 1641.4377607	total: 3.02s	remaining: 831ms
392:	learn: 1641.1288765	total: 3.02s	remaining: 823ms
393:	learn: 1640.8737725	total: 3.03s	remaining: 815ms
394:	learn: 1640.6714583	total: 3.04s	remaining: 808ms
395:	learn: 1640.4362201	total: 3.05s	remaining: 800ms
396:	learn: 1640.0727489	total: 3.05s	remaining: 792ms
397:	learn: 1639.8041299	total: 3.06s	remaining: 785ms
398:	learn: 1639.4578769	total: 3.07s	remaining: 777ms
399:	learn: 1639.1131204	total: 3.08s	remaining: 769ms
400:	learn: 1638.9662449	total: 3.08s	remaining: 761ms
401:	learn: 1638.6851426	total: 3.09s	remaining: 754ms
402:	learn: 1

46:	learn: 1909.7165710	total: 363ms	remaining: 3.5s
47:	learn: 1905.8100135	total: 370ms	remaining: 3.49s
48:	learn: 1903.6134990	total: 378ms	remaining: 3.48s
49:	learn: 1901.4991809	total: 386ms	remaining: 3.47s
50:	learn: 1898.6306630	total: 394ms	remaining: 3.47s
51:	learn: 1894.9986799	total: 401ms	remaining: 3.46s
52:	learn: 1891.3864186	total: 409ms	remaining: 3.45s
53:	learn: 1889.6035239	total: 417ms	remaining: 3.44s
54:	learn: 1887.0027585	total: 424ms	remaining: 3.43s
55:	learn: 1883.8509489	total: 432ms	remaining: 3.42s
56:	learn: 1881.5238431	total: 439ms	remaining: 3.41s
57:	learn: 1878.3438582	total: 447ms	remaining: 3.4s
58:	learn: 1876.3716168	total: 454ms	remaining: 3.4s
59:	learn: 1872.1773947	total: 462ms	remaining: 3.39s
60:	learn: 1870.0118019	total: 470ms	remaining: 3.38s
61:	learn: 1866.0866762	total: 478ms	remaining: 3.38s
62:	learn: 1863.9443429	total: 486ms	remaining: 3.37s
63:	learn: 1860.3057713	total: 493ms	remaining: 3.36s
64:	learn: 1858.8118509	total: 

202:	learn: 1714.7415622	total: 1.55s	remaining: 2.27s
203:	learn: 1714.0334561	total: 1.56s	remaining: 2.27s
204:	learn: 1713.5737303	total: 1.57s	remaining: 2.26s
205:	learn: 1713.1796647	total: 1.58s	remaining: 2.25s
206:	learn: 1712.7123768	total: 1.59s	remaining: 2.25s
207:	learn: 1712.2597388	total: 1.59s	remaining: 2.24s
208:	learn: 1711.5437800	total: 1.6s	remaining: 2.23s
209:	learn: 1711.1291267	total: 1.61s	remaining: 2.22s
210:	learn: 1710.7044532	total: 1.62s	remaining: 2.21s
211:	learn: 1710.0758587	total: 1.62s	remaining: 2.21s
212:	learn: 1709.5814424	total: 1.63s	remaining: 2.2s
213:	learn: 1708.4893181	total: 1.64s	remaining: 2.19s
214:	learn: 1707.5577516	total: 1.65s	remaining: 2.18s
215:	learn: 1707.0601394	total: 1.66s	remaining: 2.18s
216:	learn: 1706.5964504	total: 1.66s	remaining: 2.17s
217:	learn: 1706.0736725	total: 1.67s	remaining: 2.16s
218:	learn: 1705.4655491	total: 1.68s	remaining: 2.15s
219:	learn: 1704.9404917	total: 1.69s	remaining: 2.15s
220:	learn: 

358:	learn: 1646.9823978	total: 2.75s	remaining: 1.08s
359:	learn: 1646.6443715	total: 2.76s	remaining: 1.07s
360:	learn: 1646.2855343	total: 2.77s	remaining: 1.07s
361:	learn: 1645.7449318	total: 2.78s	remaining: 1.06s
362:	learn: 1645.4344418	total: 2.79s	remaining: 1.05s
363:	learn: 1645.0688750	total: 2.79s	remaining: 1.04s
364:	learn: 1644.8337405	total: 2.8s	remaining: 1.03s
365:	learn: 1644.4524441	total: 2.81s	remaining: 1.03s
366:	learn: 1644.2736530	total: 2.81s	remaining: 1.02s
367:	learn: 1643.8865803	total: 2.82s	remaining: 1.01s
368:	learn: 1643.5900660	total: 2.83s	remaining: 1s
369:	learn: 1643.3173750	total: 2.84s	remaining: 997ms
370:	learn: 1643.0811591	total: 2.85s	remaining: 990ms
371:	learn: 1642.7870685	total: 2.85s	remaining: 982ms
372:	learn: 1642.5224857	total: 2.86s	remaining: 974ms
373:	learn: 1642.1619390	total: 2.87s	remaining: 967ms
374:	learn: 1641.8905330	total: 2.88s	remaining: 959ms
375:	learn: 1641.6040697	total: 2.88s	remaining: 951ms
376:	learn: 16

20:	learn: 2101.5029440	total: 168ms	remaining: 3.83s
21:	learn: 2081.6230279	total: 176ms	remaining: 3.83s
22:	learn: 2067.5224744	total: 185ms	remaining: 3.83s
23:	learn: 2056.0951150	total: 192ms	remaining: 3.81s
24:	learn: 2047.2230145	total: 200ms	remaining: 3.8s
25:	learn: 2037.0832157	total: 208ms	remaining: 3.8s
26:	learn: 2027.2957795	total: 216ms	remaining: 3.79s
27:	learn: 2016.8627691	total: 224ms	remaining: 3.78s
28:	learn: 2010.1326688	total: 232ms	remaining: 3.77s
29:	learn: 2002.0229704	total: 239ms	remaining: 3.75s
30:	learn: 1996.6622675	total: 247ms	remaining: 3.73s
31:	learn: 1987.9154186	total: 254ms	remaining: 3.72s
32:	learn: 1978.6928729	total: 262ms	remaining: 3.71s
33:	learn: 1972.5875379	total: 270ms	remaining: 3.7s
34:	learn: 1966.6314552	total: 277ms	remaining: 3.68s
35:	learn: 1962.5068562	total: 285ms	remaining: 3.67s
36:	learn: 1957.8820713	total: 292ms	remaining: 3.65s
37:	learn: 1953.2711864	total: 300ms	remaining: 3.65s
38:	learn: 1949.4899113	total: 

176:	learn: 1728.5216525	total: 1.37s	remaining: 2.5s
177:	learn: 1728.1709668	total: 1.38s	remaining: 2.49s
178:	learn: 1727.4617869	total: 1.39s	remaining: 2.49s
179:	learn: 1726.8238109	total: 1.39s	remaining: 2.48s
180:	learn: 1726.2469325	total: 1.4s	remaining: 2.47s
181:	learn: 1725.7383155	total: 1.41s	remaining: 2.46s
182:	learn: 1725.4226508	total: 1.42s	remaining: 2.45s
183:	learn: 1724.7146379	total: 1.43s	remaining: 2.45s
184:	learn: 1724.1667648	total: 1.43s	remaining: 2.44s
185:	learn: 1723.6575319	total: 1.44s	remaining: 2.43s
186:	learn: 1722.9801294	total: 1.45s	remaining: 2.42s
187:	learn: 1722.1816899	total: 1.46s	remaining: 2.42s
188:	learn: 1721.5912505	total: 1.46s	remaining: 2.41s
189:	learn: 1721.1559937	total: 1.47s	remaining: 2.4s
190:	learn: 1720.1788895	total: 1.48s	remaining: 2.39s
191:	learn: 1719.2862671	total: 1.49s	remaining: 2.38s
192:	learn: 1718.8164802	total: 1.49s	remaining: 2.38s
193:	learn: 1718.2980326	total: 1.5s	remaining: 2.37s
194:	learn: 17

330:	learn: 1657.3067633	total: 2.57s	remaining: 1.31s
331:	learn: 1657.0215152	total: 2.58s	remaining: 1.3s
332:	learn: 1656.6778246	total: 2.59s	remaining: 1.3s
333:	learn: 1656.1652879	total: 2.6s	remaining: 1.29s
334:	learn: 1655.7511977	total: 2.6s	remaining: 1.28s
335:	learn: 1655.4542328	total: 2.61s	remaining: 1.27s
336:	learn: 1655.2083219	total: 2.62s	remaining: 1.27s
337:	learn: 1654.9022238	total: 2.63s	remaining: 1.26s
338:	learn: 1654.3498009	total: 2.63s	remaining: 1.25s
339:	learn: 1653.8527732	total: 2.64s	remaining: 1.24s
340:	learn: 1653.4449376	total: 2.65s	remaining: 1.24s
341:	learn: 1652.8866868	total: 2.66s	remaining: 1.23s
342:	learn: 1652.6513446	total: 2.66s	remaining: 1.22s
343:	learn: 1652.3491261	total: 2.67s	remaining: 1.21s
344:	learn: 1651.9076624	total: 2.68s	remaining: 1.2s
345:	learn: 1651.3866410	total: 2.69s	remaining: 1.2s
346:	learn: 1651.0884208	total: 2.69s	remaining: 1.19s
347:	learn: 1650.5210187	total: 2.7s	remaining: 1.18s
348:	learn: 1650.

487:	learn: 1609.8106323	total: 3.77s	remaining: 92.8ms
488:	learn: 1609.4937022	total: 3.78s	remaining: 85.1ms
489:	learn: 1609.3545168	total: 3.79s	remaining: 77.4ms
490:	learn: 1609.1410443	total: 3.8s	remaining: 69.6ms
491:	learn: 1608.9330797	total: 3.81s	remaining: 61.9ms
492:	learn: 1608.8865638	total: 3.81s	remaining: 54.1ms
493:	learn: 1608.5437344	total: 3.82s	remaining: 46.4ms
494:	learn: 1608.3170101	total: 3.83s	remaining: 38.7ms
495:	learn: 1608.0632440	total: 3.84s	remaining: 30.9ms
496:	learn: 1607.6604702	total: 3.84s	remaining: 23.2ms
497:	learn: 1607.4389879	total: 3.85s	remaining: 15.5ms
498:	learn: 1607.1513029	total: 3.86s	remaining: 7.73ms
499:	learn: 1606.9515248	total: 3.87s	remaining: 0us
Learning rate set to 0.5
0:	learn: 3198.0225568	total: 8.8ms	remaining: 871ms
1:	learn: 2615.8441227	total: 17.7ms	remaining: 869ms
2:	learn: 2358.1713340	total: 26.6ms	remaining: 859ms
3:	learn: 2218.7035989	total: 35.6ms	remaining: 854ms
4:	learn: 2137.2419387	total: 44.3ms

41:	learn: 1767.3675801	total: 365ms	remaining: 505ms
42:	learn: 1764.0965507	total: 374ms	remaining: 496ms
43:	learn: 1761.1283503	total: 383ms	remaining: 488ms
44:	learn: 1757.0370248	total: 392ms	remaining: 479ms
45:	learn: 1754.5997148	total: 401ms	remaining: 471ms
46:	learn: 1750.8973232	total: 410ms	remaining: 462ms
47:	learn: 1749.1173835	total: 419ms	remaining: 454ms
48:	learn: 1746.8912412	total: 427ms	remaining: 445ms
49:	learn: 1744.2059879	total: 436ms	remaining: 436ms
50:	learn: 1741.6675544	total: 445ms	remaining: 427ms
51:	learn: 1739.1063605	total: 453ms	remaining: 418ms
52:	learn: 1734.6459019	total: 462ms	remaining: 410ms
53:	learn: 1731.8136774	total: 471ms	remaining: 401ms
54:	learn: 1729.1659144	total: 480ms	remaining: 393ms
55:	learn: 1725.2463040	total: 489ms	remaining: 384ms
56:	learn: 1722.8041243	total: 498ms	remaining: 375ms
57:	learn: 1720.6867044	total: 506ms	remaining: 367ms
58:	learn: 1718.6605846	total: 515ms	remaining: 358ms
59:	learn: 1716.8100500	tota

Learning rate set to 0.243349
0:	learn: 3820.5726396	total: 9.21ms	remaining: 2.75s
1:	learn: 3331.7902380	total: 18.8ms	remaining: 2.81s
2:	learn: 2974.2262359	total: 27.4ms	remaining: 2.71s
3:	learn: 2725.6727958	total: 36ms	remaining: 2.66s
4:	learn: 2551.5747056	total: 44.3ms	remaining: 2.61s
5:	learn: 2431.2067774	total: 53ms	remaining: 2.6s
6:	learn: 2339.6896406	total: 61.5ms	remaining: 2.57s
7:	learn: 2270.3757061	total: 70.2ms	remaining: 2.56s
8:	learn: 2210.6179864	total: 78.9ms	remaining: 2.55s
9:	learn: 2161.3926300	total: 87.6ms	remaining: 2.54s
10:	learn: 2122.9559691	total: 96.6ms	remaining: 2.54s
11:	learn: 2092.2191799	total: 105ms	remaining: 2.53s
12:	learn: 2066.0051010	total: 114ms	remaining: 2.51s
13:	learn: 2043.6498926	total: 122ms	remaining: 2.5s
14:	learn: 2026.9173808	total: 131ms	remaining: 2.49s
15:	learn: 2006.5359560	total: 140ms	remaining: 2.48s
16:	learn: 1991.4067417	total: 148ms	remaining: 2.46s
17:	learn: 1978.0817800	total: 157ms	remaining: 2.46s
18:

160:	learn: 1664.2192417	total: 1.38s	remaining: 1.19s
161:	learn: 1663.1878716	total: 1.39s	remaining: 1.19s
162:	learn: 1662.2281219	total: 1.4s	remaining: 1.18s
163:	learn: 1661.5892240	total: 1.41s	remaining: 1.17s
164:	learn: 1660.8596463	total: 1.42s	remaining: 1.16s
165:	learn: 1660.2713237	total: 1.42s	remaining: 1.15s
166:	learn: 1659.7360379	total: 1.43s	remaining: 1.14s
167:	learn: 1658.9768660	total: 1.44s	remaining: 1.13s
168:	learn: 1658.3281548	total: 1.45s	remaining: 1.12s
169:	learn: 1657.4798479	total: 1.46s	remaining: 1.11s
170:	learn: 1656.0434244	total: 1.47s	remaining: 1.11s
171:	learn: 1655.3385017	total: 1.48s	remaining: 1.1s
172:	learn: 1654.4824388	total: 1.48s	remaining: 1.09s
173:	learn: 1653.9229793	total: 1.49s	remaining: 1.08s
174:	learn: 1653.1768557	total: 1.5s	remaining: 1.07s
175:	learn: 1652.4074103	total: 1.51s	remaining: 1.06s
176:	learn: 1651.3009641	total: 1.52s	remaining: 1.05s
177:	learn: 1650.8609616	total: 1.52s	remaining: 1.04s
178:	learn: 1

18:	learn: 1973.3618935	total: 166ms	remaining: 2.46s
19:	learn: 1962.6250918	total: 175ms	remaining: 2.46s
20:	learn: 1949.0624376	total: 185ms	remaining: 2.45s
21:	learn: 1943.1801944	total: 193ms	remaining: 2.44s
22:	learn: 1931.8029210	total: 202ms	remaining: 2.44s
23:	learn: 1922.5144483	total: 211ms	remaining: 2.42s
24:	learn: 1915.8178526	total: 219ms	remaining: 2.41s
25:	learn: 1909.4037454	total: 227ms	remaining: 2.39s
26:	learn: 1902.1051915	total: 236ms	remaining: 2.38s
27:	learn: 1894.4322655	total: 244ms	remaining: 2.37s
28:	learn: 1889.3509234	total: 253ms	remaining: 2.36s
29:	learn: 1883.8889317	total: 261ms	remaining: 2.35s
30:	learn: 1879.6267768	total: 269ms	remaining: 2.33s
31:	learn: 1875.9541594	total: 278ms	remaining: 2.33s
32:	learn: 1870.2345975	total: 287ms	remaining: 2.32s
33:	learn: 1867.3436260	total: 295ms	remaining: 2.31s
34:	learn: 1863.5169944	total: 304ms	remaining: 2.3s
35:	learn: 1859.9901415	total: 313ms	remaining: 2.29s
36:	learn: 1856.8541532	total

185:	learn: 1646.4556339	total: 1.58s	remaining: 967ms
186:	learn: 1645.7634359	total: 1.59s	remaining: 959ms
187:	learn: 1645.4236508	total: 1.6s	remaining: 951ms
188:	learn: 1645.3033256	total: 1.6s	remaining: 943ms
189:	learn: 1644.7341739	total: 1.61s	remaining: 934ms
190:	learn: 1643.3328926	total: 1.62s	remaining: 925ms
191:	learn: 1642.2829342	total: 1.63s	remaining: 917ms
192:	learn: 1641.3309367	total: 1.64s	remaining: 908ms
193:	learn: 1640.1217176	total: 1.65s	remaining: 900ms
194:	learn: 1639.1692660	total: 1.66s	remaining: 892ms
195:	learn: 1638.4050309	total: 1.66s	remaining: 883ms
196:	learn: 1637.4980163	total: 1.67s	remaining: 875ms
197:	learn: 1636.8529801	total: 1.68s	remaining: 866ms
198:	learn: 1635.9527523	total: 1.69s	remaining: 858ms
199:	learn: 1635.6578844	total: 1.7s	remaining: 849ms
200:	learn: 1635.1539134	total: 1.71s	remaining: 840ms
201:	learn: 1634.5774754	total: 1.71s	remaining: 832ms
202:	learn: 1634.1486936	total: 1.72s	remaining: 823ms
203:	learn: 1

41:	learn: 1831.8797745	total: 363ms	remaining: 2.23s
42:	learn: 1828.0407974	total: 371ms	remaining: 2.22s
43:	learn: 1823.8456602	total: 381ms	remaining: 2.21s
44:	learn: 1820.7772600	total: 389ms	remaining: 2.21s
45:	learn: 1818.3096639	total: 398ms	remaining: 2.2s
46:	learn: 1815.2886676	total: 407ms	remaining: 2.19s
47:	learn: 1812.1326798	total: 416ms	remaining: 2.18s
48:	learn: 1810.4795275	total: 424ms	remaining: 2.17s
49:	learn: 1807.4979633	total: 433ms	remaining: 2.16s
50:	learn: 1805.8347394	total: 440ms	remaining: 2.15s
51:	learn: 1803.1624939	total: 449ms	remaining: 2.14s
52:	learn: 1799.6885681	total: 458ms	remaining: 2.13s
53:	learn: 1797.7349484	total: 466ms	remaining: 2.12s
54:	learn: 1795.5905865	total: 474ms	remaining: 2.11s
55:	learn: 1793.6189043	total: 483ms	remaining: 2.1s
56:	learn: 1790.7793546	total: 492ms	remaining: 2.1s
57:	learn: 1787.2467261	total: 500ms	remaining: 2.09s
58:	learn: 1782.8090399	total: 509ms	remaining: 2.08s
59:	learn: 1781.1676975	total: 

208:	learn: 1627.0660476	total: 1.78s	remaining: 777ms
209:	learn: 1626.4795285	total: 1.79s	remaining: 769ms
210:	learn: 1625.7005723	total: 1.8s	remaining: 761ms
211:	learn: 1624.8433636	total: 1.81s	remaining: 752ms
212:	learn: 1624.1905432	total: 1.82s	remaining: 743ms
213:	learn: 1623.5654241	total: 1.83s	remaining: 735ms
214:	learn: 1623.0056564	total: 1.84s	remaining: 726ms
215:	learn: 1622.5272116	total: 1.84s	remaining: 718ms
216:	learn: 1621.8073067	total: 1.85s	remaining: 709ms
217:	learn: 1621.3424481	total: 1.86s	remaining: 700ms
218:	learn: 1620.8215209	total: 1.87s	remaining: 692ms
219:	learn: 1620.1935011	total: 1.88s	remaining: 683ms
220:	learn: 1619.8696559	total: 1.89s	remaining: 674ms
221:	learn: 1619.5622455	total: 1.89s	remaining: 666ms
222:	learn: 1619.0762557	total: 1.9s	remaining: 657ms
223:	learn: 1618.6881825	total: 1.91s	remaining: 648ms
224:	learn: 1618.2676828	total: 1.92s	remaining: 640ms
225:	learn: 1617.8756322	total: 1.93s	remaining: 631ms
226:	learn: 

65:	learn: 1823.0551497	total: 569ms	remaining: 3.74s
66:	learn: 1821.0085797	total: 578ms	remaining: 3.74s
67:	learn: 1819.8054939	total: 588ms	remaining: 3.73s
68:	learn: 1817.0086946	total: 597ms	remaining: 3.73s
69:	learn: 1815.9308403	total: 605ms	remaining: 3.72s
70:	learn: 1813.9288166	total: 614ms	remaining: 3.71s
71:	learn: 1811.4363428	total: 623ms	remaining: 3.7s
72:	learn: 1809.4745268	total: 631ms	remaining: 3.69s
73:	learn: 1808.4213141	total: 640ms	remaining: 3.68s
74:	learn: 1807.0787011	total: 648ms	remaining: 3.67s
75:	learn: 1805.8887612	total: 656ms	remaining: 3.66s
76:	learn: 1803.9185012	total: 664ms	remaining: 3.65s
77:	learn: 1802.6474426	total: 672ms	remaining: 3.64s
78:	learn: 1801.5064067	total: 680ms	remaining: 3.63s
79:	learn: 1799.4189335	total: 689ms	remaining: 3.62s
80:	learn: 1797.2824715	total: 697ms	remaining: 3.61s
81:	learn: 1796.1012109	total: 705ms	remaining: 3.59s
82:	learn: 1793.7431133	total: 714ms	remaining: 3.59s
83:	learn: 1792.3420124	total

231:	learn: 1662.4429771	total: 1.98s	remaining: 2.29s
232:	learn: 1661.7498143	total: 1.99s	remaining: 2.28s
233:	learn: 1661.2448827	total: 2s	remaining: 2.27s
234:	learn: 1660.6453617	total: 2.01s	remaining: 2.26s
235:	learn: 1660.2039134	total: 2.02s	remaining: 2.26s
236:	learn: 1659.8527286	total: 2.02s	remaining: 2.25s
237:	learn: 1659.1631750	total: 2.03s	remaining: 2.24s
238:	learn: 1658.7319649	total: 2.04s	remaining: 2.23s
239:	learn: 1658.1955936	total: 2.05s	remaining: 2.22s
240:	learn: 1657.5804022	total: 2.06s	remaining: 2.21s
241:	learn: 1657.0045874	total: 2.07s	remaining: 2.2s
242:	learn: 1656.6211589	total: 2.08s	remaining: 2.19s
243:	learn: 1656.1770480	total: 2.08s	remaining: 2.19s
244:	learn: 1655.4526489	total: 2.09s	remaining: 2.18s
245:	learn: 1655.2466042	total: 2.1s	remaining: 2.17s
246:	learn: 1654.4112620	total: 2.11s	remaining: 2.16s
247:	learn: 1654.0110159	total: 2.12s	remaining: 2.15s
248:	learn: 1653.5638377	total: 2.13s	remaining: 2.14s
249:	learn: 165

399:	learn: 1593.3132091	total: 3.41s	remaining: 852ms
400:	learn: 1592.9586101	total: 3.42s	remaining: 844ms
401:	learn: 1592.7371641	total: 3.43s	remaining: 835ms
402:	learn: 1592.4887658	total: 3.43s	remaining: 827ms
403:	learn: 1592.2334006	total: 3.44s	remaining: 818ms
404:	learn: 1592.0315924	total: 3.45s	remaining: 810ms
405:	learn: 1591.6010275	total: 3.46s	remaining: 801ms
406:	learn: 1591.3717435	total: 3.47s	remaining: 793ms
407:	learn: 1591.1476842	total: 3.48s	remaining: 784ms
408:	learn: 1590.7376701	total: 3.48s	remaining: 775ms
409:	learn: 1590.5521907	total: 3.49s	remaining: 767ms
410:	learn: 1590.3179473	total: 3.5s	remaining: 758ms
411:	learn: 1590.0293071	total: 3.51s	remaining: 750ms
412:	learn: 1589.5686939	total: 3.52s	remaining: 741ms
413:	learn: 1589.3503957	total: 3.53s	remaining: 733ms
414:	learn: 1589.0336141	total: 3.54s	remaining: 724ms
415:	learn: 1588.7906431	total: 3.54s	remaining: 716ms
416:	learn: 1588.4649639	total: 3.55s	remaining: 707ms
417:	learn:

66:	learn: 1823.2173994	total: 570ms	remaining: 3.69s
67:	learn: 1821.3136602	total: 579ms	remaining: 3.68s
68:	learn: 1819.2037287	total: 589ms	remaining: 3.68s
69:	learn: 1815.7911294	total: 597ms	remaining: 3.67s
70:	learn: 1814.6912455	total: 605ms	remaining: 3.65s
71:	learn: 1812.4709358	total: 614ms	remaining: 3.65s
72:	learn: 1810.8932245	total: 622ms	remaining: 3.63s
73:	learn: 1809.3830174	total: 630ms	remaining: 3.62s
74:	learn: 1807.4562798	total: 638ms	remaining: 3.62s
75:	learn: 1805.8257829	total: 647ms	remaining: 3.61s
76:	learn: 1803.8848410	total: 655ms	remaining: 3.6s
77:	learn: 1801.8744305	total: 664ms	remaining: 3.59s
78:	learn: 1800.3132079	total: 672ms	remaining: 3.58s
79:	learn: 1797.3728411	total: 681ms	remaining: 3.57s
80:	learn: 1796.1317180	total: 689ms	remaining: 3.56s
81:	learn: 1793.9657937	total: 697ms	remaining: 3.55s
82:	learn: 1792.9797040	total: 705ms	remaining: 3.54s
83:	learn: 1790.7080160	total: 713ms	remaining: 3.53s
84:	learn: 1789.6393720	total

234:	learn: 1659.5965797	total: 1.98s	remaining: 2.24s
235:	learn: 1659.2696637	total: 1.99s	remaining: 2.23s
236:	learn: 1658.4607788	total: 2s	remaining: 2.22s
237:	learn: 1657.7798366	total: 2.01s	remaining: 2.21s
238:	learn: 1657.3503061	total: 2.02s	remaining: 2.2s
239:	learn: 1656.9352040	total: 2.03s	remaining: 2.19s
240:	learn: 1656.1887881	total: 2.04s	remaining: 2.19s
241:	learn: 1655.5066982	total: 2.04s	remaining: 2.18s
242:	learn: 1654.5953835	total: 2.05s	remaining: 2.17s
243:	learn: 1654.0441913	total: 2.06s	remaining: 2.16s
244:	learn: 1653.5676820	total: 2.07s	remaining: 2.15s
245:	learn: 1653.4288277	total: 2.08s	remaining: 2.14s
246:	learn: 1652.8047600	total: 2.09s	remaining: 2.14s
247:	learn: 1652.3103781	total: 2.09s	remaining: 2.13s
248:	learn: 1651.9572976	total: 2.1s	remaining: 2.12s
249:	learn: 1651.6848249	total: 2.11s	remaining: 2.11s
250:	learn: 1651.2360419	total: 2.12s	remaining: 2.1s
251:	learn: 1650.8244806	total: 2.13s	remaining: 2.09s
252:	learn: 1650

401:	learn: 1591.2241350	total: 3.39s	remaining: 827ms
402:	learn: 1590.9912112	total: 3.4s	remaining: 819ms
403:	learn: 1590.7054751	total: 3.41s	remaining: 810ms
404:	learn: 1590.0138611	total: 3.42s	remaining: 802ms
405:	learn: 1589.7321191	total: 3.43s	remaining: 794ms
406:	learn: 1589.3552467	total: 3.44s	remaining: 785ms
407:	learn: 1588.8429737	total: 3.44s	remaining: 777ms
408:	learn: 1588.4697335	total: 3.45s	remaining: 768ms
409:	learn: 1587.9105538	total: 3.46s	remaining: 760ms
410:	learn: 1587.4808452	total: 3.47s	remaining: 751ms
411:	learn: 1587.1193345	total: 3.48s	remaining: 743ms
412:	learn: 1586.9647349	total: 3.49s	remaining: 735ms
413:	learn: 1586.6017592	total: 3.5s	remaining: 726ms
414:	learn: 1586.2587240	total: 3.5s	remaining: 718ms
415:	learn: 1586.1825626	total: 3.51s	remaining: 709ms
416:	learn: 1585.8456639	total: 3.52s	remaining: 701ms
417:	learn: 1585.6075812	total: 3.53s	remaining: 692ms
418:	learn: 1585.4073824	total: 3.54s	remaining: 684ms
419:	learn: 1

65:	learn: 1822.2587770	total: 569ms	remaining: 3.74s
66:	learn: 1820.2240628	total: 577ms	remaining: 3.73s
67:	learn: 1818.6222430	total: 586ms	remaining: 3.72s
68:	learn: 1816.4848662	total: 595ms	remaining: 3.72s
69:	learn: 1814.7271721	total: 603ms	remaining: 3.71s
70:	learn: 1812.4111966	total: 612ms	remaining: 3.7s
71:	learn: 1809.6653168	total: 621ms	remaining: 3.69s
72:	learn: 1806.2970485	total: 630ms	remaining: 3.68s
73:	learn: 1804.3948875	total: 638ms	remaining: 3.67s
74:	learn: 1803.0376247	total: 647ms	remaining: 3.67s
75:	learn: 1801.5451587	total: 656ms	remaining: 3.66s
76:	learn: 1800.1152418	total: 664ms	remaining: 3.65s
77:	learn: 1797.5489421	total: 673ms	remaining: 3.64s
78:	learn: 1796.2132978	total: 682ms	remaining: 3.63s
79:	learn: 1793.4014915	total: 690ms	remaining: 3.62s
80:	learn: 1791.3319738	total: 699ms	remaining: 3.61s
81:	learn: 1789.9016332	total: 706ms	remaining: 3.6s
82:	learn: 1786.9288327	total: 715ms	remaining: 3.59s
83:	learn: 1785.7669995	total:

231:	learn: 1660.4675331	total: 1.98s	remaining: 2.29s
232:	learn: 1659.9887731	total: 1.99s	remaining: 2.28s
233:	learn: 1659.3044288	total: 2s	remaining: 2.27s
234:	learn: 1658.9860951	total: 2.01s	remaining: 2.26s
235:	learn: 1658.5240992	total: 2.02s	remaining: 2.25s
236:	learn: 1658.1242228	total: 2.02s	remaining: 2.25s
237:	learn: 1657.5062459	total: 2.03s	remaining: 2.24s
238:	learn: 1656.8084871	total: 2.04s	remaining: 2.23s
239:	learn: 1656.2920098	total: 2.05s	remaining: 2.22s
240:	learn: 1656.1091028	total: 2.06s	remaining: 2.21s
241:	learn: 1655.6090595	total: 2.06s	remaining: 2.2s
242:	learn: 1655.0027743	total: 2.07s	remaining: 2.19s
243:	learn: 1654.4253742	total: 2.08s	remaining: 2.19s
244:	learn: 1653.8937284	total: 2.09s	remaining: 2.18s
245:	learn: 1653.5537301	total: 2.1s	remaining: 2.17s
246:	learn: 1653.2014295	total: 2.11s	remaining: 2.16s
247:	learn: 1652.7240945	total: 2.11s	remaining: 2.15s
248:	learn: 1652.0503358	total: 2.12s	remaining: 2.14s
249:	learn: 165

398:	learn: 1591.8633988	total: 3.39s	remaining: 859ms
399:	learn: 1591.5837721	total: 3.4s	remaining: 851ms
400:	learn: 1591.2559988	total: 3.41s	remaining: 842ms
401:	learn: 1590.9492265	total: 3.42s	remaining: 833ms
402:	learn: 1590.5396694	total: 3.43s	remaining: 825ms
403:	learn: 1590.2115748	total: 3.44s	remaining: 816ms
404:	learn: 1589.8504699	total: 3.44s	remaining: 808ms
405:	learn: 1589.4391785	total: 3.45s	remaining: 799ms
406:	learn: 1589.1067805	total: 3.46s	remaining: 791ms
407:	learn: 1588.7490932	total: 3.47s	remaining: 782ms
408:	learn: 1588.5051574	total: 3.48s	remaining: 774ms
409:	learn: 1588.3648372	total: 3.48s	remaining: 765ms
410:	learn: 1588.2495427	total: 3.49s	remaining: 757ms
411:	learn: 1588.0263412	total: 3.5s	remaining: 748ms
412:	learn: 1587.7548425	total: 3.51s	remaining: 740ms
413:	learn: 1587.5152152	total: 3.52s	remaining: 731ms
414:	learn: 1587.1904615	total: 3.53s	remaining: 723ms
415:	learn: 1586.7528359	total: 3.54s	remaining: 714ms
416:	learn: 

49:	learn: 1855.1503161	total: 555ms	remaining: 5s
50:	learn: 1852.4354275	total: 569ms	remaining: 5.01s
51:	learn: 1850.3572751	total: 580ms	remaining: 4.99s
52:	learn: 1847.7228111	total: 591ms	remaining: 4.98s
53:	learn: 1845.1688809	total: 602ms	remaining: 4.97s
54:	learn: 1842.4397099	total: 612ms	remaining: 4.95s
55:	learn: 1839.5348112	total: 623ms	remaining: 4.94s
56:	learn: 1837.7981018	total: 633ms	remaining: 4.92s
57:	learn: 1834.9610023	total: 645ms	remaining: 4.91s
58:	learn: 1832.8901465	total: 656ms	remaining: 4.9s
59:	learn: 1831.1200563	total: 666ms	remaining: 4.89s
60:	learn: 1828.7760403	total: 677ms	remaining: 4.87s
61:	learn: 1827.2502832	total: 687ms	remaining: 4.85s
62:	learn: 1823.9850458	total: 698ms	remaining: 4.84s
63:	learn: 1821.8279845	total: 709ms	remaining: 4.83s
64:	learn: 1819.4682954	total: 720ms	remaining: 4.82s
65:	learn: 1817.8557412	total: 731ms	remaining: 4.81s
66:	learn: 1816.7908877	total: 741ms	remaining: 4.79s
67:	learn: 1815.4303014	total: 7

201:	learn: 1678.4283097	total: 2.21s	remaining: 3.25s
202:	learn: 1677.9713810	total: 2.22s	remaining: 3.24s
203:	learn: 1677.4996370	total: 2.23s	remaining: 3.23s
204:	learn: 1676.9497714	total: 2.24s	remaining: 3.22s
205:	learn: 1676.5027813	total: 2.25s	remaining: 3.21s
206:	learn: 1675.9934479	total: 2.26s	remaining: 3.2s
207:	learn: 1675.6548791	total: 2.27s	remaining: 3.19s
208:	learn: 1675.1459041	total: 2.28s	remaining: 3.17s
209:	learn: 1674.6990756	total: 2.29s	remaining: 3.16s
210:	learn: 1674.1334677	total: 2.3s	remaining: 3.15s
211:	learn: 1673.8136919	total: 2.31s	remaining: 3.14s
212:	learn: 1673.2062415	total: 2.32s	remaining: 3.13s
213:	learn: 1672.4432618	total: 2.33s	remaining: 3.12s
214:	learn: 1671.8661057	total: 2.34s	remaining: 3.11s
215:	learn: 1671.0911141	total: 2.35s	remaining: 3.1s
216:	learn: 1670.5344741	total: 2.37s	remaining: 3.08s
217:	learn: 1669.9665117	total: 2.38s	remaining: 3.07s
218:	learn: 1669.4819659	total: 2.39s	remaining: 3.06s
219:	learn: 1

353:	learn: 1614.5963650	total: 3.84s	remaining: 1.58s
354:	learn: 1614.3149483	total: 3.86s	remaining: 1.57s
355:	learn: 1614.0144598	total: 3.87s	remaining: 1.56s
356:	learn: 1613.6154710	total: 3.88s	remaining: 1.55s
357:	learn: 1613.3800620	total: 3.89s	remaining: 1.54s
358:	learn: 1612.9929903	total: 3.9s	remaining: 1.53s
359:	learn: 1612.7339536	total: 3.91s	remaining: 1.52s
360:	learn: 1612.4781527	total: 3.92s	remaining: 1.51s
361:	learn: 1612.0618188	total: 3.93s	remaining: 1.5s
362:	learn: 1611.5115512	total: 3.94s	remaining: 1.49s
363:	learn: 1611.2745059	total: 3.95s	remaining: 1.48s
364:	learn: 1611.0116554	total: 3.96s	remaining: 1.47s
365:	learn: 1610.9592780	total: 3.97s	remaining: 1.45s
366:	learn: 1610.5564803	total: 3.98s	remaining: 1.44s
367:	learn: 1610.3603827	total: 3.99s	remaining: 1.43s
368:	learn: 1610.0382323	total: 4s	remaining: 1.42s
369:	learn: 1609.7712076	total: 4.02s	remaining: 1.41s
370:	learn: 1609.4520927	total: 4.03s	remaining: 1.4s
371:	learn: 1609

In [67]:
print('Лучшее значение RMSE в CatBoost:', round(abs(result_cat.best_score_)**0.5, 2))
print('Лучшие параметры CatBoost:', result_cat.best_params_)
print('Время выполнения кода:', time_cat)

Лучшее значение RMSE в CatBoost: 1659.83
Лучшие параметры CatBoost: {'depth': 7, 'grow_policy': 'SymmetricTree', 'iterations': 500}
Время выполнения кода: 0:01:38.500856


lightGBM выполнила 405 операций за 6 минут, это примерно 68 операций в минуту, CatBoost выполнила 36 операций за 1 минуту 40 сенкунд, это примерно 20 операций в минуту. CatBoost заметно дольше, даже с параметром grow_policy = SymmetricTree. RMSE этих моделей при этом примерно равны.

In [68]:
# Найдем время обучения и предсказания модели CatBoost
start_time = datetime.now()
best_model_cat = search_cat.best_estimator_
best_model_cat.fit(features_train, target_train)
end_time = datetime.now()
time_cat_fit = end_time - start_time

start_time = datetime.now()
predictions=best_model_cat.predict(features_test)
end_time = datetime.now()
time_cat_predict = end_time - start_time
print('Время обучения модели CatBoost:', time_cat_fit)
print('Время предсказания модели CatBoost:', time_cat_predict)

Learning rate set to 0.177406
0:	learn: 4000.0839490	total: 11.1ms	remaining: 5.56s
1:	learn: 3588.8727232	total: 23ms	remaining: 5.72s
2:	learn: 3271.8316376	total: 34.5ms	remaining: 5.71s
3:	learn: 3029.8388760	total: 45.8ms	remaining: 5.68s
4:	learn: 2838.5385902	total: 57ms	remaining: 5.64s
5:	learn: 2691.5534057	total: 68.4ms	remaining: 5.63s
6:	learn: 2574.1743190	total: 79.6ms	remaining: 5.61s
7:	learn: 2469.9204232	total: 90.9ms	remaining: 5.59s
8:	learn: 2391.9739028	total: 102ms	remaining: 5.56s
9:	learn: 2330.0668724	total: 113ms	remaining: 5.54s
10:	learn: 2274.7322595	total: 124ms	remaining: 5.52s
11:	learn: 2229.4254382	total: 135ms	remaining: 5.5s
12:	learn: 2191.8060942	total: 147ms	remaining: 5.5s
13:	learn: 2159.4647418	total: 158ms	remaining: 5.49s
14:	learn: 2131.4380617	total: 171ms	remaining: 5.54s
15:	learn: 2105.7283992	total: 183ms	remaining: 5.53s
16:	learn: 2084.9648161	total: 195ms	remaining: 5.53s
17:	learn: 2068.1496135	total: 206ms	remaining: 5.51s
18:	le

162:	learn: 1705.3925784	total: 1.78s	remaining: 3.69s
163:	learn: 1704.4709016	total: 1.8s	remaining: 3.68s
164:	learn: 1703.4844068	total: 1.81s	remaining: 3.67s
165:	learn: 1702.9498143	total: 1.82s	remaining: 3.66s
166:	learn: 1702.1700433	total: 1.83s	remaining: 3.65s
167:	learn: 1701.4955745	total: 1.84s	remaining: 3.64s
168:	learn: 1700.9637909	total: 1.85s	remaining: 3.63s
169:	learn: 1700.2644911	total: 1.86s	remaining: 3.62s
170:	learn: 1699.3738811	total: 1.87s	remaining: 3.6s
171:	learn: 1698.6515611	total: 1.88s	remaining: 3.59s
172:	learn: 1697.9840170	total: 1.89s	remaining: 3.58s
173:	learn: 1697.5398967	total: 1.91s	remaining: 3.57s
174:	learn: 1697.0114203	total: 1.92s	remaining: 3.56s
175:	learn: 1696.1632674	total: 1.93s	remaining: 3.55s
176:	learn: 1695.3415980	total: 1.94s	remaining: 3.54s
177:	learn: 1694.9063331	total: 1.95s	remaining: 3.52s
178:	learn: 1694.4232891	total: 1.96s	remaining: 3.51s
179:	learn: 1693.7251748	total: 1.97s	remaining: 3.5s
180:	learn: 1

314:	learn: 1627.3489562	total: 3.43s	remaining: 2.01s
315:	learn: 1627.0363120	total: 3.44s	remaining: 2s
316:	learn: 1626.5856011	total: 3.45s	remaining: 1.99s
317:	learn: 1626.3317005	total: 3.46s	remaining: 1.98s
318:	learn: 1626.1045603	total: 3.47s	remaining: 1.97s
319:	learn: 1625.7834386	total: 3.48s	remaining: 1.96s
320:	learn: 1625.3938703	total: 3.49s	remaining: 1.95s
321:	learn: 1625.1533936	total: 3.51s	remaining: 1.94s
322:	learn: 1625.0001720	total: 3.52s	remaining: 1.93s
323:	learn: 1624.7568506	total: 3.53s	remaining: 1.92s
324:	learn: 1624.3204153	total: 3.54s	remaining: 1.91s
325:	learn: 1623.9146296	total: 3.55s	remaining: 1.9s
326:	learn: 1623.4298682	total: 3.56s	remaining: 1.89s
327:	learn: 1623.1056296	total: 3.58s	remaining: 1.88s
328:	learn: 1622.8480942	total: 3.59s	remaining: 1.86s
329:	learn: 1622.5916260	total: 3.6s	remaining: 1.85s
330:	learn: 1622.3070311	total: 3.61s	remaining: 1.84s
331:	learn: 1621.8229251	total: 3.62s	remaining: 1.83s
332:	learn: 162

481:	learn: 1577.2922012	total: 5.26s	remaining: 196ms
482:	learn: 1577.0439433	total: 5.27s	remaining: 186ms
483:	learn: 1576.8494692	total: 5.28s	remaining: 175ms
484:	learn: 1576.4882023	total: 5.29s	remaining: 164ms
485:	learn: 1576.2506039	total: 5.3s	remaining: 153ms
486:	learn: 1575.9728646	total: 5.32s	remaining: 142ms
487:	learn: 1575.8030354	total: 5.33s	remaining: 131ms
488:	learn: 1575.5450284	total: 5.34s	remaining: 120ms
489:	learn: 1575.3516529	total: 5.35s	remaining: 109ms
490:	learn: 1575.1109710	total: 5.36s	remaining: 98.2ms
491:	learn: 1574.7068710	total: 5.37s	remaining: 87.3ms
492:	learn: 1574.5790355	total: 5.38s	remaining: 76.4ms
493:	learn: 1574.1816022	total: 5.39s	remaining: 65.5ms
494:	learn: 1573.8301426	total: 5.4s	remaining: 54.6ms
495:	learn: 1573.4543669	total: 5.41s	remaining: 43.7ms
496:	learn: 1573.2920941	total: 5.42s	remaining: 32.7ms
497:	learn: 1573.0736422	total: 5.43s	remaining: 21.8ms
498:	learn: 1572.8522128	total: 5.45s	remaining: 10.9ms
499

In [84]:
# Перенесем результаты в единую таблицу
data = [['fit', time_lr_fit, time_lgbm_fit, time_xgb_fit, time_cat_fit],
       ['predict', time_lr_predict, time_lgbm_predict, time_xgb_predict, time_cat_predict]]
df_time = pd.DataFrame(data = data, columns = ['process', 'lin_reg', 'LightGBM', 'XGBoost', 'CatBoost'])
df_time

process                lin_reg               LightGBM  \
0      fit 0 days 00:00:02.601249 0 days 00:00:02.104028   
1  predict 0 days 00:00:00.145788 0 days 00:00:00.335054   

                 XGBoost               CatBoost  
0 0 days 00:01:08.542189 0 days 00:00:05.833271  
1 0 days 00:00:00.261927 0 days 00:00:00.032638

## Выводы

- В ходе работы мы изучили данные
- Удалили дубликаты в данных; заполнили пропуски в колонках с моделью, типом кузова, типом топлива, информацией о ремонте автомобиля
- Написали функцию для нахождения самого частого типа кузова при определенной марке и модели автомобиля, заполнили пропуски в типах кузова
- Обучили различные модели: линейную регрессию, LightGBM, XGBoost, CatBoost, а так же сравнили скорость обучения моделей
- На наших данных быстрее всего обучается модель LightGBM, и лучшее значение RMSE = 1634 принадлежит этой модели.